// Agencia de Viajes/Movent/src/components/Comentarionodo.vue
<template>
  <div class="cn-nodo">
    <div class="cn-card">

      <!-- Layout: columna votos + cuerpo -->
      <div class="cn-layout">

        <!-- Columna de votos estilo Reddit -->
        <div class="cn-votes"
          :class="{ 'cn-votes--up': votoActual === 1, 'cn-votes--down': votoActual === -1 }">

          <button
            class="cn-arrow cn-arrow--up"
            :class="{ 'cn-arrow--active': votoActual === 1 }"
            @click="emit('votar', comentario.id, 1)"
            :disabled="!haySession"
            :title="haySession ? 'Útil' : 'Inicia sesión para votar'"
            type="button"
          >
            <svg viewBox="0 0 24 24"
              :fill="votoActual === 1 ? 'currentColor' : 'none'"
              stroke="currentColor" stroke-width="2.5"
              width="14" height="14">
              <polyline points="18 15 12 9 6 15"/>
            </svg>
          </button>

          <span class="cn-score" :class="scoreClass">
            {{ score > 0 ? '+' : '' }}{{ score }}
          </span>

          <button
            class="cn-arrow cn-arrow--down"
            :class="{ 'cn-arrow--active': votoActual === -1 }"
            @click="emit('votar', comentario.id, -1)"
            :disabled="!haySession"
            :title="haySession ? 'No útil' : 'Inicia sesión para votar'"
            type="button"
          >
            <svg viewBox="0 0 24 24"
              :fill="votoActual === -1 ? 'currentColor' : 'none'"
              stroke="currentColor" stroke-width="2.5"
              width="14" height="14">
              <polyline points="6 9 12 15 18 9"/>
            </svg>
          </button>

        </div>

        <!-- Cuerpo del comentario -->
        <div class="cn-body">

          <div class="cn-header">
            <div class="cn-user">
              <div class="cn-avatar">
                {{ (comentario.nombreCompleto ?? comentario.username)?.charAt(0)?.toUpperCase() ?? '?' }}
              </div>
              <div class="cn-user-info">
                <span class="cn-nombre">
                  {{ comentario.nombreCompleto ?? comentario.username }}
                </span>
                <span class="cn-username">@{{ comentario.username }}</span>
              </div>
            </div>
            <span class="cn-fecha">{{ formatFecha(comentario.fecha) }}</span>
          </div>

          <!-- Estrellas: vuelo usa cantidadEstrellas, hotel usa resena -->
          <div v-if="estrellas !== null" class="cn-estrellas">
            <svg v-for="n in 5" :key="n" viewBox="0 0 24 24"
              :fill="n <= estrellas ? 'currentColor' : 'none'"
              stroke="currentColor" stroke-width="2"
              class="cn-estrella" :class="{ 'cn-estrella--llena': n <= estrellas }"
              width="14" height="14">
              <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
            </svg>
          </div>

          <p class="cn-contenido">{{ comentario.contenido }}</p>

          <!-- Acciones -->
          <div class="cn-acciones">
            <button v-if="haySession"
              class="cn-responder-btn"
              @click="emit('toggleForm', comentario.id)"
              type="button">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12">
                <polyline points="9 17 4 12 9 7"/>
                <path d="M20 18v-2a4 4 0 0 0-4-4H4"/>
              </svg>
              {{ estado.mostrandoForm ? 'Cancelar' : 'Responder' }}
            </button>

            <button v-if="hijos.length > 0"
              class="cn-ver-mas"
              :class="{ 'cn-ver-mas--expanded': estado.expandido }"
              @click="emit('toggleExpandido', comentario.id)"
              type="button">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"
                :style="{ transform: estado.expandido ? 'rotate(180deg)' : 'none', transition: 'transform .2s' }">
                <polyline points="6 9 12 15 18 9"/>
              </svg>
              {{ estado.expandido
                ? 'Ocultar respuestas'
                : `Ver ${hijos.length} ${hijos.length === 1 ? 'respuesta' : 'respuestas'}` }}
            </button>
          </div>

          <!-- Formulario de respuesta -->
          <div v-if="estado.mostrandoForm" class="cn-reply-form">
            <textarea
              :value="estado.textoRespuesta"
              @input="emit('textoChange', comentario.id, ($event.target as HTMLTextAreaElement).value)"
              placeholder="Escribe tu respuesta..."
              rows="3"
              class="cn-reply-textarea"
            ></textarea>
            <div class="cn-reply-actions">
              <button class="cn-reply-cancel"
                @click="emit('toggleForm', comentario.id)" type="button">
                Cancelar
              </button>
              <button class="cn-reply-submit"
                @click="emit('enviarRespuesta', comentario.id)"
                :disabled="!estado.textoRespuesta?.trim() || estado.enviando"
                type="button">
                <span v-if="estado.enviando" class="cn-spin"></span>
                {{ estado.enviando ? 'Enviando...' : 'Responder' }}
              </button>
            </div>
          </div>

        </div>
      </div>

      <!-- Hijos recursivos -->
      <div v-if="hijos.length > 0 && estado.expandido" class="cn-hilo">
        <div class="cn-hilo-linea"></div>
        <div class="cn-hilo-respuestas">
          <ComentarioNodo
            v-for="hijo in hijos"
            :key="hijo.id"
            :comentario="hijo"
            :getHijos="getHijos"
            :estadoNodos="estadoNodos"
            :haySession="haySession"
            :formatFecha="formatFecha"
            :profundidad="(profundidad ?? 0) + 1"
            @votar="(id, voto) => emit('votar', id, voto)"
            @toggleForm="(id) => emit('toggleForm', id)"
            @toggleExpandido="(id) => emit('toggleExpandido', id)"
            @enviarRespuesta="(id) => emit('enviarRespuesta', id)"
            @textoChange="(id, txt) => emit('textoChange', id, txt)"
          />
        </div>
      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
// @ts-ignore
import '../styles/ComentarioNodo.css'

defineOptions({ name: 'ComentarioNodo' })

const props = defineProps<{
  comentario: {
    id: number
    username: string
    nombreCompleto?: string
    cantidadEstrellas?: number | null
    resena?: number | null
    contenido: string
    fecha: string
    downs: number
    comentarioPadreId: number | null
  }
  getHijos: (id: number) => any[]
  estadoNodos: Record<number, {
    expandido: boolean
    mostrandoForm: boolean
    textoRespuesta: string
    enviando: boolean
    votoActual: 1 | -1 | null
  }>
  haySession: boolean
  formatFecha: (fecha: string) => string
  profundidad?: number
}>()

const emit = defineEmits<{
  (e: 'votar',           id: number, voto: 1 | -1): void
  (e: 'toggleForm',      id: number): void
  (e: 'toggleExpandido', id: number): void
  (e: 'enviarRespuesta', id: number): void
  (e: 'textoChange',     id: number, texto: string): void
}>()

const hijos      = computed(() => props.getHijos(props.comentario.id))
const estado     = computed(() => props.estadoNodos[props.comentario.id] ?? {
  expandido: false, mostrandoForm: false,
  textoRespuesta: '', enviando: false, votoActual: null
})
const votoActual = computed(() => estado.value.votoActual)
const score      = computed(() => props.comentario.downs ?? 0)
const scoreClass = computed(() =>
  score.value > 0 ? 'cn-score--pos' : score.value < 0 ? 'cn-score--neg' : 'cn-score--zero'
)
const estrellas  = computed(() => {
  const v = props.comentario.cantidadEstrellas ?? props.comentario.resena ?? null
  return (v !== null && v !== undefined) ? v : null
})
</script>

// Aero Linea/AirLine Broom/src/pages/ComentarioNodo.svelte
<script>
  // @ts-nocheck
  // ComentarioNodo.svelte — comentario recursivo con votos estilo Reddit

  export let comentario;
  export let getHijos;
  export let estadoNodos;
  export let haySession;
  export let formatFecha;
  export let getEstrellas;
  export let votar;
  export let toggleForm;
  export let toggleExpandido;
  export let enviarRespuesta;
  export let onTextoChange;
  export let profundidad = 0;

  import ComentarioNodo from './ComentarioNodo.svelte';

  $: hijos  = getHijos(comentario.id);
  $: estado = estadoNodos[comentario.id] ?? {
    expandido: false,
    mostrandoForm: false,
    textoRespuesta: '',
    enviando: false,
    votoActual: null
  };
  $: votoActual = estado.votoActual;

  // `downs` en la API es el score neto. Se envía +1 / -1 al votar.
  $: score = comentario.downs ?? 0;
  $: scoreClass = score > 0 ? 'score-pos' : score < 0 ? 'score-neg' : 'score-zero';
</script>

<div class="dv-comentario-nodo">
  <div class="dv-comentario-card">

    <!-- Layout: columna votos + cuerpo -->
    <div class="dv-cmt-layout">

      <!-- Columna de votos estilo Reddit -->
      <div class="dv-cmt-votes" class:voted-up={votoActual === 1} class:voted-down={votoActual === -1}>

        <button
          class="dv-vote-arrow dv-vote-arrow--up"
          class:dv-vote-arrow--active={votoActual === 1}
          on:click={() => votar(comentario.id, 1)}
          disabled={!haySession}
          title={haySession ? 'Útil' : 'Inicia sesión para votar'}
          aria-label="Voto positivo"
        >
          <svg viewBox="0 0 24 24" fill={votoActual === 1 ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="2.5">
            <polyline points="18 15 12 9 6 15"/>
          </svg>
        </button>

        <span class="dv-vote-score {scoreClass}">
          {score > 0 ? '+' : ''}{score}
        </span>

        <button
          class="dv-vote-arrow dv-vote-arrow--down"
          class:dv-vote-arrow--active={votoActual === -1}
          on:click={() => votar(comentario.id, -1)}
          disabled={!haySession}
          title={haySession ? 'No útil' : 'Inicia sesión para votar'}
          aria-label="Voto negativo"
        >
          <svg viewBox="0 0 24 24" fill={votoActual === -1 ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="2.5">
            <polyline points="6 9 12 15 18 9"/>
          </svg>
        </button>

      </div>

      <!-- Cuerpo -->
      <div class="dv-cmt-body">

        <div class="dv-comentario-header">
          <div class="dv-comentario-user">
            <div class="dv-comentario-avatar">
              {comentario.nombreCompleto?.charAt(0)?.toUpperCase() ?? '?'}
            </div>
            <div class="dv-comentario-user-info">
              <div class="dv-comentario-nombre">{comentario.nombreCompleto}</div>
              <div class="dv-comentario-username">@{comentario.username}</div>
            </div>
          </div>
          <div class="dv-comentario-fecha">{formatFecha(comentario.fecha)}</div>
        </div>

        {#if comentario.cantidadEstrellas !== null && comentario.cantidadEstrellas !== undefined}
          <div class="dv-comentario-estrellas">
            {#each getEstrellas(comentario.cantidadEstrellas) as llena}
              <svg class="dv-estrella" class:dv-estrella--llena={llena}
                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                fill={llena ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="2">
                <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
              </svg>
            {/each}
          </div>
        {/if}

        <div class="dv-comentario-contenido">{comentario.contenido}</div>

        <div class="dv-comentario-acciones">
          {#if haySession}
            <button class="dv-responder-btn" on:click={() => toggleForm(comentario.id)}>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="9 17 4 12 9 7"/>
                <path d="M20 18v-2a4 4 0 0 0-4-4H4"/>
              </svg>
              {estado.mostrandoForm ? 'Cancelar' : 'Responder'}
            </button>
          {:else}
            <span class="dv-login-hint">Inicia sesión para responder</span>
          {/if}

          {#if hijos.length > 0}
            <button
              class="dv-ver-mas"
              class:dv-ver-mas--expanded={estado.expandido}
              on:click={() => toggleExpandido(comentario.id)}
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="6 9 12 15 18 9"/>
              </svg>
              {estado.expandido
                ? 'Ocultar respuestas'
                : `Ver ${hijos.length} ${hijos.length === 1 ? 'respuesta' : 'respuestas'}`}
            </button>
          {/if}
        </div>

        {#if estado.mostrandoForm}
          <div class="dv-reply-form">
            <textarea
              placeholder="Escribe tu respuesta..."
              value={estado.textoRespuesta}
              on:input={e => onTextoChange(comentario.id, e.target.value)}
              rows="3"
            ></textarea>
            <div class="dv-reply-actions">
              <button class="dv-reply-cancel" on:click={() => toggleForm(comentario.id)}>Cancelar</button>
              <button
                class="dv-reply-submit"
                on:click={() => enviarRespuesta(comentario.id)}
                disabled={!estado.textoRespuesta.trim() || estado.enviando}
              >
                {estado.enviando ? 'Enviando...' : 'Responder'}
              </button>
            </div>
          </div>
        {/if}

      </div>
    </div>

    <!-- Hijos recursivos -->
    {#if hijos.length > 0 && estado.expandido}
      <div class="dv-comentario-hilo">
        <div class="dv-hilo-linea"></div>
        <div class="dv-hilo-respuestas">
          {#each hijos as hijo (hijo.id)}
            <svelte:self
              comentario={hijo}
              {getHijos}
              {estadoNodos}
              {haySession}
              {formatFecha}
              {getEstrellas}
              {votar}
              {toggleForm}
              {toggleExpandido}
              {enviarRespuesta}
              {onTextoChange}
              profundidad={profundidad + 1}
            />
          {/each}
        </div>
      </div>
    {/if}

  </div>
</div>
