// Agencia de Viajes/Movent/src/views/Seleccionasientos.vue
<template>
  <div class="page">
    <Encabezado />

    <!-- ═══ OVERLAY: Reserva expirada ═══ -->
    <div v-if="tiempoRestante === 0" class="asi-overlay">
      <div class="asi-overlay__card asi-overlay__card--error">
        <svg viewBox="0 0 24 24" fill="none" stroke="#D40511" stroke-width="1.5" width="52" height="52">
          <circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>
        </svg>
        <h3 class="asi-overlay__titulo">Reserva expirada</h3>
        <p class="asi-overlay__msg">El tiempo para completar la reserva ha vencido.</p>
        <button class="asi-btn asi-btn--yellow" @click="$router.push('/principal')" type="button">
          Realizar nueva búsqueda
        </button>
      </div>
    </div>

    <div class="asi-page">
      <div class="asi-container">

        <!-- ═══ HEADER ═══ -->
        <div class="asi-header">
          <button class="asi-back" @click="$router.push('/reserva')" type="button">
            ← Datos pasajeros
          </button>
          <div class="asi-titulo">
            <h1 class="asi-titulo__main">Selección de Asientos</h1>
            <p class="asi-titulo__sub" v-if="grupoActual">
              {{ grupoActual.avionMarca }} {{ grupoActual.avionModelo }}
              &nbsp;·&nbsp; Vuelo {{ grupoActual.numeroVuelo }}
              &nbsp;·&nbsp; {{ boletosActuales.length }} pasajero{{ boletosActuales.length > 1 ? 's' : '' }}
              <template v-if="totalGrupos > 1">
                &nbsp;·&nbsp; <strong>Vuelo {{ grupoActualIdx + 1 }} de {{ totalGrupos }}</strong>
              </template>
            </p>
          </div>
          <!-- Timer -->
          <div v-if="tiempoRestante > 0" class="asi-timer"
            :class="{
              'asi-timer--warn':    tiempoRestante <= 180 && tiempoRestante > 60,
              'asi-timer--urgente': tiempoRestante <= 60,
            }">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14">
              <circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>
            </svg>
            {{ formatTiempo(tiempoRestante) }}
          </div>
        </div>

        <!-- ═══ PROGRESO MULTI-VUELO ═══ -->
        <div v-if="totalGrupos > 1" class="asi-vuelos-prog">
          <template v-for="(g, i) in flightGroups" :key="i">
            <div class="asi-vuelos-prog__item"
              :class="{
                'asi-vuelos-prog__item--activo':    i === grupoActualIdx,
                'asi-vuelos-prog__item--completo':  i < grupoActualIdx,
              }">
              <span class="asi-vuelos-prog__num">{{ i + 1 }}</span>
              <span class="asi-vuelos-prog__label">{{ g.numeroVuelo }}</span>
            </div>
            <div v-if="i < totalGrupos - 1" class="asi-vuelos-prog__linea"
              :class="{ 'asi-vuelos-prog__linea--completa': i < grupoActualIdx }"></div>
          </template>
        </div>

        <!-- ═══ ESTADO: CARGANDO / ERROR ═══ -->
        <div v-if="loading" class="asi-estado">
          <div class="asi-spinner"></div>
          <span>Cargando mapa de asientos...</span>
        </div>
        <div v-else-if="error" class="asi-estado asi-estado--error">
          <svg viewBox="0 0 24 24" fill="none" stroke="#D40511" stroke-width="1.5" width="28" height="28">
            <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
          </svg>
          {{ error }}
          <button class="asi-btn asi-btn--ghost" @click="cargarAsientos" style="margin-top:8px">Reintentar</button>
        </div>

        <!-- ═══ BODY ═══ -->
        <div v-else-if="grupoActual" class="asi-body">

          <!-- ══ MAPA DEL AVIÓN ══ -->
          <div class="asi-mapa-wrap">

            <!-- Nariz -->
            <div class="asi-avion-nariz">
              <svg viewBox="0 0 220 90" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M110 4 C70 4, 14 30, 10 58 L10 86 L210 86 L210 58 C206 30, 150 4, 110 4Z"
                  fill="#1C1A18" stroke="#c9a96e" stroke-width="1.2"/>
                <path d="M110 14 C78 14, 28 36, 24 60 L24 78 L196 78 L196 60 C192 36, 142 14, 110 14Z"
                  fill="#2c2a24" stroke="#c9a96e" stroke-width="0.6" opacity="0.6"/>
                <ellipse cx="68"  cy="50" rx="8" ry="5" fill="#FFCC00" opacity="0.25"/>
                <ellipse cx="110" cy="44" rx="8" ry="5" fill="#FFCC00" opacity="0.25"/>
                <ellipse cx="152" cy="50" rx="8" ry="5" fill="#FFCC00" opacity="0.25"/>
                <text x="110" y="73" text-anchor="middle" fill="#c9a96e"
                  font-size="9" letter-spacing="3" font-family="inherit">CABINA</text>
              </svg>
            </div>

            <!-- Cuerpo del avión -->
            <div class="asi-avion-cuerpo">

              <!-- Cabecera columnas -->
              <div class="asi-cols-header">
                <div class="asi-fila-num"></div>
                <template v-for="(lbl, ci) in COLS_LABEL" :key="ci">
                  <div v-if="ci === 3" class="asi-pasillo"></div>
                  <div class="asi-col-lbl">{{ lbl }}</div>
                </template>
              </div>

              <!-- Zona Ejecutiva -->
              <div class="asi-zona-lbl asi-zona-lbl--eje"><span>Ejecutiva</span></div>
              <div v-for="fila in filasEjeActuales" :key="'eje-'+fila" class="asi-fila asi-fila--eje">
                <div class="asi-fila-num">{{ fila }}</div>
                <template v-for="ci in 6" :key="ci">
                  <div v-if="ci === 4" class="asi-pasillo"></div>
                  <button
                    :class="['asi-seat', 'asi-seat--eje', claseAsiento(asientos[idEje(fila, ci)])]"
                    :disabled="guardando || esBloqueado(asientos[idEje(fila, ci)])"
                    @click="seleccionarAsiento(asientos[idEje(fila, ci)])"
                    :title="`E-${fila}${ci}`"
                    type="button"
                  >
                    <span v-if="asientos[idEje(fila, ci)]?.estado === 'propio'" class="asi-seat__num">
                      {{ indicePasajero(idEje(fila, ci)) + 1 }}
                    </span>
                  </button>
                </template>
              </div>

              <!-- Separador cabina -->
              <div class="asi-separador">
                <div class="asi-separador__linea"></div>
                <span class="asi-separador__lbl">Separador de Cabina</span>
                <div class="asi-separador__linea"></div>
              </div>

              <!-- Zona Turista -->
              <div class="asi-zona-lbl asi-zona-lbl--tur"><span>Turista</span></div>
              <div v-for="fila in filasTActuales" :key="'tur-'+fila" class="asi-fila">
                <div class="asi-fila-num">{{ fila }}</div>
                <template v-for="ci in 6" :key="ci">
                  <div v-if="ci === 4" class="asi-pasillo"></div>
                  <button
                    :class="['asi-seat', claseAsiento(asientos[idTur(fila, ci)])]"
                    :disabled="guardando || esBloqueado(asientos[idTur(fila, ci)])"
                    @click="seleccionarAsiento(asientos[idTur(fila, ci)])"
                    :title="`${fila}${ci}`"
                    type="button"
                  >
                    <span v-if="asientos[idTur(fila, ci)]?.estado === 'propio'" class="asi-seat__num">
                      {{ indicePasajero(idTur(fila, ci)) + 1 }}
                    </span>
                  </button>
                </template>
              </div>

            </div><!-- /avion-cuerpo -->

            <!-- Cola -->
            <div class="asi-avion-cola">
              <svg viewBox="0 0 220 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 0 L210 0 L210 24 C180 44, 140 50, 110 50 C80 50, 40 44, 10 24 Z"
                  fill="#1C1A18" stroke="#c9a96e" stroke-width="1.2"/>
              </svg>
            </div>

          </div><!-- /mapa-wrap -->

          <!-- ══ SIDEBAR ══ -->
          <aside class="asi-sidebar">

            <!-- Progreso selección -->
            <div class="asi-progreso">
              <div class="asi-progreso__header">
                <span class="asi-progreso__titulo">Pasajeros</span>
                <span class="asi-progreso__conteo">
                  {{ seleccionados.filter(Boolean).length }} / {{ boletosActuales.length }}
                </span>
              </div>
              <div class="asi-progreso__barra">
                <div class="asi-progreso__fill" :style="{ width: progreso + '%' }"></div>
              </div>
              <p v-if="guardando" class="asi-progreso__guardando">
                <span class="asi-spinner-sm"></span> Guardando asiento...
              </p>
              <p v-if="errorGuardar" class="asi-progreso__error">{{ errorGuardar }}</p>
            </div>

            <!-- Lista pasajeros -->
            <div class="asi-pax-lista">
              <div v-for="(b, i) in boletosActuales" :key="b.boletoId"
                class="asi-pax-item"
                :class="{
                  'asi-pax-item--activo':   i === pasajeroActual && !todoSeleccionado,
                  'asi-pax-item--completo': !!seleccionados[i],
                }"
                @click="pasajeroActual = i"
                role="button" tabindex="0">
                <div class="asi-pax-item__num">{{ i + 1 }}</div>
                <div class="asi-pax-item__info">
                  <span class="asi-pax-item__label">Pasajero {{ i + 1 }}</span>
                  <span class="asi-pax-item__asiento">
                    {{ seleccionados[i] ? `Asiento ${seleccionados[i]}` : 'Sin asignar' }}
                  </span>
                  <span class="asi-pax-item__clase">{{ b.claseId === 2 ? 'Ejecutiva' : 'Turista' }}</span>
                </div>
              </div>
            </div>

            <!-- Leyenda -->
            <div class="asi-leyenda">
              <h3 class="asi-leyenda__titulo">Leyenda</h3>
              <div class="asi-leyenda__items">
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--libre asi-seat--muestra"></div>
                  <span>Disponible</span>
                </div>
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--seleccionado asi-seat--muestra"></div>
                  <span>Tuyo</span>
                </div>
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--ocupado asi-seat--muestra"></div>
                  <span>Ocupado</span>
                </div>
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--bloqueado asi-seat--muestra"></div>
                  <span>Otra clase</span>
                </div>
              </div>
            </div>

            <!-- Botón continuar -->
            <button class="asi-continuar"
              :class="{ 'asi-continuar--listo': todoSeleccionado && !guardando }"
              :disabled="!todoSeleccionado || guardando"
              @click="handleContinuar"
              type="button">
              <template v-if="guardando">Guardando...</template>
              <template v-else-if="!todoSeleccionado">
                Selecciona {{ boletosActuales.length - seleccionados.filter(Boolean).length }}
                asiento{{ (boletosActuales.length - seleccionados.filter(Boolean).length) !== 1 ? 's' : '' }} más
              </template>
              <template v-else-if="!esUltimoGrupo">Siguiente vuelo →</template>
              <template v-else>Confirmar Asientos ✓</template>
            </button>

          </aside>
        </div><!-- /body -->

      </div>
    </div>

    <Piepagina />
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import Encabezado from '../components/Encabezado.vue'
import Piepagina from '../components/Piepagina.vue'
import '../styles/Seleccionasientos.css'

const router = useRouter()
const API    = 'http://localhost:8080'

// ── Constantes ────────────────────────────────────────────────
const COLS_LABEL = ['A','B','C','D','E','F']

// ── Timer ─────────────────────────────────────────────────────
const tiempoRestante = ref(0)
const tiempoTotal    = ref(600)
const timerInterval  = ref(null)

function formatTiempo(s) {
  return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`
}
function iniciarTimer(segs) {
  tiempoRestante.value = segs
  tiempoTotal.value    = segs
  if (timerInterval.value) clearInterval(timerInterval.value)
  timerInterval.value = setInterval(() => {
    tiempoRestante.value = Math.max(0, tiempoRestante.value - 1)
    if (tiempoRestante.value === 0) clearInterval(timerInterval.value)
  }, 1000)
}
onUnmounted(() => { if (timerInterval.value) clearInterval(timerInterval.value) })

// ── Datos de sesión ───────────────────────────────────────────
const reservacionId = ref(null)
const proveedorId   = ref(null)

// ── Estado vuelos ─────────────────────────────────────────────
const flightGroups   = ref([])   // respuesta completa de la API
const grupoActualIdx = ref(0)
const loading        = ref(true)
const error          = ref(null)
const guardando      = ref(false)
const errorGuardar   = ref(null)

// ── Estado selección del grupo actual ────────────────────────
const asientos       = ref({})   // mapa id → { id, fila, col, clase, estado }
const seleccionados  = ref([])   // [asientoId | null] por índice de pasajero
const pasajeroActual = ref(0)

// ── Computed del grupo actual ─────────────────────────────────
const grupoActual    = computed(() => flightGroups.value[grupoActualIdx.value] ?? null)
const totalGrupos    = computed(() => flightGroups.value.length)
const esUltimoGrupo  = computed(() => grupoActualIdx.value === totalGrupos.value - 1)
const boletosActuales = computed(() => grupoActual.value?.boletosAgencia ?? [])

// Clase del pasajero activo determina qué zona puede usar
const claseActual = computed(() => {
  const b = boletosActuales.value[pasajeroActual.value]
  return b?.claseId === 2 ? 'Ejecutiva' : 'Turista'
})

const filasEjeActuales = computed(() => {
  const g = grupoActual.value
  if (!g) return []
  return [...generarLetras(g.filasEjecutiva)]
})
const filasTActuales = computed(() => {
  const g = grupoActual.value
  if (!g) return []
  return [...generarLetras(g.totalFilas - g.filasEjecutiva)]
})

const progreso = computed(() => {
  const n = boletosActuales.value.length
  if (!n) return 0
  return (seleccionados.value.filter(Boolean).length / n) * 100
})
const todoSeleccionado = computed(() =>
  boletosActuales.value.length > 0 &&
  seleccionados.value.length === boletosActuales.value.length &&
  seleccionados.value.every(Boolean)
)

// ── Generadores de letras: A,B,...,Z,AA,AB,... ───────────────
function* generarLetras(cantidad) {
  const abc = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  for (let i = 0; i < cantidad; i++) {
    let s = '', n = i
    do { s = abc[n % 26] + s; n = Math.floor(n / 26) - 1 } while (n >= 0)
    yield s
  }
}

// IDs backend
function idEje(fila, col) { return `E-${fila}${col}` }
function idTur(fila, col) { return `${fila}${col}`   }

// ── onMounted ─────────────────────────────────────────────────
onMounted(async () => {
  // Recuperar IDs de reserva
  const raw = sessionStorage.getItem('checkout_data')
  if (!raw) { router.push('/principal'); return }

  const cd = JSON.parse(raw)
  reservacionId.value = cd.reservacionId
  proveedorId.value   = cd.proveedorId

  // Restaurar timer desde sessionStorage
  const expAt = sessionStorage.getItem('_reserva_expires_at')
  if (expAt) {
    const segs = Math.floor((Number(expAt) - Date.now()) / 1000)
    if (segs > 0) iniciarTimer(segs)
  }

  await cargarAsientos()
})

// ── Carga de asientos desde API ───────────────────────────────
async function cargarAsientos() {
  loading.value = true; error.value = null

  try {
    const res = await fetch(`${API}/api/reservaciones/asientos-vuelo`, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        reservacion_id: reservacionId.value,
        proveedor_id:   proveedorId.value,
      }),
    })
    if (!res.ok) {
      const e = await res.json().catch(() => ({}))
      throw new Error(e.error ?? `Error ${res.status} al cargar asientos.`)
    }
    flightGroups.value = await res.json()
    if (!flightGroups.value.length) throw new Error('No se recibieron datos de vuelos.')
    construirMapa(0)
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

// ── Construir mapa de asientos para un grupo ─────────────────
function construirMapa(idx) {
  const grupo = flightGroups.value[idx]
  if (!grupo) return

  const ocupados = new Set(grupo.asientosOcupados ?? [])
  const boletos  = grupo.boletosAgencia ?? []

  // Inicializar seleccionados con los asientos ya asignados
  seleccionados.value = boletos.map(b => b.asiento ?? null)
  const primerLibre   = seleccionados.value.findIndex(s => !s)
  pasajeroActual.value = primerLibre === -1 ? 0 : primerLibre

  const mapa = {}

  // Ejecutiva: E-A1..E-{filasEje}6
  for (const fila of generarLetras(grupo.filasEjecutiva)) {
    for (let col = 1; col <= 6; col++) {
      const id = idEje(fila, col)
      mapa[id] = {
        id, fila, col, clase: 'Ejecutiva',
        estado: ocupados.has(id)          ? 'ocupado'
              : seleccionados.value.includes(id) ? 'propio'
              : 'libre',
      }
    }
  }

  // Turista: A1..{filasT}6
  for (const fila of generarLetras(grupo.totalFilas - grupo.filasEjecutiva)) {
    for (let col = 1; col <= 6; col++) {
      const id = idTur(fila, col)
      mapa[id] = {
        id, fila, col, clase: 'Turista',
        estado: ocupados.has(id)          ? 'ocupado'
              : seleccionados.value.includes(id) ? 'propio'
              : 'libre',
      }
    }
  }

  asientos.value = mapa
}

// ── Lógica de asientos ────────────────────────────────────────
function esBloqueado(a) {
  if (!a) return true
  if (a.estado === 'ocupado') return true
  if (a.estado === 'propio')  return false   // siempre clickeable para cambiar foco
  if (claseActual.value === 'Ejecutiva' && a.clase !== 'Ejecutiva') return true
  if (claseActual.value === 'Turista'   && a.clase !== 'Turista')   return true
  return false
}

function claseAsiento(a) {
  if (!a) return 'asi-seat--vacio'
  if (a.estado === 'ocupado') return 'asi-seat--ocupado'
  if (a.estado === 'propio')  return 'asi-seat--seleccionado'
  // No bloquear visualmente si el pasajero activo puede usarlo
  const puedePasajeroActual =
    (claseActual.value === 'Ejecutiva' && a.clase === 'Ejecutiva') ||
    (claseActual.value === 'Turista'   && a.clase === 'Turista')
  if (!puedePasajeroActual) return 'asi-seat--bloqueado'
  return 'asi-seat--libre'
}

function indicePasajero(id) { return seleccionados.value.indexOf(id) }

async function seleccionarAsiento(a) {
  if (guardando.value || !a || a.estado === 'ocupado') return

  // Click en asiento propio → solo cambiar foco al pasajero
  if (a.estado === 'propio') {
    const idx = seleccionados.value.indexOf(a.id)
    if (idx !== -1) pasajeroActual.value = idx
    return
  }

  // Verificar clase
  if (claseActual.value === 'Ejecutiva' && a.clase !== 'Ejecutiva') return
  if (claseActual.value === 'Turista'   && a.clase !== 'Turista')   return
  if (seleccionados.value[pasajeroActual.value] === a.id) return

  const boleto         = boletosActuales.value[pasajeroActual.value]
  const asientoAnterior = seleccionados.value[pasajeroActual.value]
  if (!boleto) return

  guardando.value = true; errorGuardar.value = null

  try {
    const res = await fetch(`${API}/api/reservaciones/asientos-vuelo`, {
      method: 'PUT',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        reservacion_id: reservacionId.value,
        proveedor_id:   proveedorId.value,
        boleto_id:      boleto.boletoId,
        nuevo_asiento:  a.id,
      }),
    })
    if (!res.ok) {
      const e = await res.json().catch(() => ({}))
      throw new Error(e.error ?? 'Error al cambiar asiento.')
    }

    // Actualizar mapa local sin recargar
    const nuevoMapa = { ...asientos.value }
    if (asientoAnterior && nuevoMapa[asientoAnterior]) {
      nuevoMapa[asientoAnterior] = { ...nuevoMapa[asientoAnterior], estado: 'libre' }
    }
    nuevoMapa[a.id] = { ...nuevoMapa[a.id], estado: 'propio' }
    asientos.value  = nuevoMapa

    const nuevaSel = [...seleccionados.value]
    nuevaSel[pasajeroActual.value] = a.id
    seleccionados.value = nuevaSel

    // Avanzar al siguiente pasajero sin asiento
    const sig = nuevaSel.findIndex((s, i) => i > pasajeroActual.value && !s)
    if (sig !== -1) pasajeroActual.value = sig

  } catch (e) {
    errorGuardar.value = e.message
  } finally {
    guardando.value = false
  }
}

// ── Continuar / Confirmar ─────────────────────────────────────
function handleContinuar() {
  if (!todoSeleccionado.value || guardando.value) return

  if (!esUltimoGrupo.value) {
    grupoActualIdx.value++
    construirMapa(grupoActualIdx.value)
  } else {
    // Todos los vuelos tienen asientos → ir al checkout
    if (timerInterval.value) clearInterval(timerInterval.value)
    sessionStorage.removeItem('_reserva_expires_at')
    sessionStorage.removeItem('_reserva_id')
    sessionStorage.removeItem('_reserva_no')
    router.push('/checkout')
  }
}
</script>

// Aero Linea/AirLine Broom/src/pages/Seleccionasientos.svelte
<script>
  // @ts-nocheck
  import '../styles/asientos.css';
  import { onMount } from 'svelte';

  export let navigateTo;
  export let flightData = [];

  const API = 'https://localhost:7107';

  // ── Nomenclatura del backend ─────────────────────────────────────────────
  // Las FILAS son NÚMEROS (1, 2, 3...) y las COLUMNAS son LETRAS (A-F).
  //
  // Ejecutiva: E-A1..E-F1, E-A2..E-F2, ... (fila numérica, col letra)
  //   → ID = "E-{colLetra}{numFila}"   ej: E-A1, E-B1, E-C2
  // Turista:   A1..F1, A2..F2, ...
  //   → ID = "{colLetra}{numFila}"     ej: A1, B1, C2
  //
  // Visualmente: número de fila en el margen izquierdo, letras A-F arriba.

  const NUM_COLUMNAS    = 6;
  const FILAS_EJECUTIVA = 4;
  const COLS_LABEL      = ['A','B','C','D','E','F'];

  // ── Grupos de vuelo ──────────────────────────────────────────────────────
  let grupoActualIdx = 0;
  $: grupoActual   = flightData?.[grupoActualIdx] ?? null;
  $: totalGrupos   = flightData?.length ?? 0;
  $: esUltimoGrupo = grupoActualIdx === totalGrupos - 1;

  $: vueloId          = grupoActual?.vueloId      ?? null;
  $: numeroVuelo      = grupoActual?.numeroVuelo   ?? '';
  $: avionModelo      = grupoActual?.avionModelo   ?? '';
  $: avionMarca       = grupoActual?.avionMarca    ?? '';
  $: claseActual      = grupoActual?.clase         ?? 'Turista';
  $: pasajerosTotales = grupoActual?.boletos?.length ?? 1;

  // ── Estado ───────────────────────────────────────────────────────────────
  let loading      = true;
  let error        = null;
  let guardando    = false;
  let errorGuardar = null;

  let totalFilas       = 0;
  let asientosOcupados = new Set();
  let boletosUsuario   = [];
  let asientos         = {};   // clave = id backend exacto
  let seleccionados    = [];
  let pasajeroActual   = 0;

  // ── IDs backend ──────────────────────────────────────────────────────────
  // fila  = número (1,2,3...)   col = letra ('A','B',...)
  function idEjecutiva(fila, col) { return `E-${col}${fila}`; }
  function idTurista(fila, col)   { return `${col}${fila}`;   }

  // ── Filas reactivas ──────────────────────────────────────────────────────
  // Ejecutiva: siempre 4 filas numéricas [1,2,3,4]
  $: filasEje = Array.from({ length: FILAS_EJECUTIVA }, (_, i) => i + 1);
  // Turista: filas dinámicas según totalFilas
  $: filasT = totalFilas > FILAS_EJECUTIVA
      ? Array.from({ length: totalFilas - FILAS_EJECUTIVA }, (_, i) => i + 1)
      : [];

  // ── onMount ──────────────────────────────────────────────────────────────
  onMount(async () => {
    if (!flightData || flightData.length === 0) {
      error = 'No se recibió información de vuelos.';
      loading = false;
      return;
    }
    await cargarAsientos();
  });

  let ultimoGrupoIdx = -1;
  $: if (grupoActualIdx !== ultimoGrupoIdx && vueloId) {
    ultimoGrupoIdx = grupoActualIdx;
    cargarAsientos();
  }

  async function cargarAsientos() {
    if (!vueloId) return;
    loading = true; error = null; errorGuardar = null;
    try {
      const res = await fetch(`${API}/api/asientos/${vueloId}`, { credentials: 'include' });
      if (!res.ok) { const e = await res.json(); throw new Error(e.message ?? 'Error al cargar asientos.'); }
      const data = await res.json();

      totalFilas       = data.totalFilas;
      asientosOcupados = new Set(data.asientosOcupados ?? []);
      boletosUsuario   = data.boletosUsuario ?? [];
      seleccionados    = boletosUsuario.map(b => b.asiento);
      pasajeroActual   = 0;
      construirMapa(data.totalFilas);
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  // ── Construir mapa de asientos ───────────────────────────────────────────
  // Filas = números (1..N), Columnas = letras (A-F)
  // ID ejecutiva: E-{colLetra}{numFila}  →  E-A1, E-B1, E-A2...
  // ID turista:   {colLetra}{numFila}    →  A1, B1, A2...
  function construirMapa(totalF) {
    const mapa = {};
    const filasT = totalF - FILAS_EJECUTIVA;

    // ── Ejecutiva: filas 1..FILAS_EJECUTIVA, columnas A-F ────────────────
    for (let row = 1; row <= FILAS_EJECUTIVA; row++) {
      for (const col of COLS_LABEL) {
        const id = idEjecutiva(row, col);
        mapa[id] = {
          id, fila: row, col,
          clase: 'Ejecutiva',
          estado: asientosOcupados.has(id) ? 'ocupado'
                : seleccionados.includes(id) ? 'propio'
                : 'libre'
        };
      }
    }

    // ── Turista: filas 1..filasT, columnas A-F ────────────────────────────
    for (let row = 1; row <= filasT; row++) {
      for (const col of COLS_LABEL) {
        const id = idTurista(row, col);
        mapa[id] = {
          id, fila: row, col,
          clase: 'Turista',
          estado: asientosOcupados.has(id) ? 'ocupado'
                : seleccionados.includes(id) ? 'propio'
                : 'libre'
        };
      }
    }

    asientos = mapa;
  }

  // ── Selección ────────────────────────────────────────────────────────────
  function puedeSeleccionar(a) {
    if (!a) return false;
    if (a.estado === 'ocupado') return false;
    if (claseActual === 'Ejecutiva' && a.clase !== 'Ejecutiva') return false;
    if (claseActual === 'Turista'   && a.clase !== 'Turista')   return false;
    return true;
  }

  function esBloqueado(a) {
    if (!a) return true;
    if (a.estado === 'ocupado') return true;
    if (a.estado === 'propio')  return false; // siempre clickeable para cambiar foco
    if (claseActual === 'Ejecutiva' && a.clase !== 'Ejecutiva') return true;
    if (claseActual === 'Turista'   && a.clase !== 'Turista')   return true;
    return false;
  }

  function indicePasajero(id) { return seleccionados.indexOf(id); }

  async function seleccionarAsiento(a) {
    if (guardando || !a || a.estado === 'ocupado') return;

    // Click en asiento propio → solo cambiar foco al pasajero correspondiente
    if (a.estado === 'propio') {
      const idx = seleccionados.indexOf(a.id);
      if (idx !== -1) pasajeroActual = idx;
      return;
    }

    if (!puedeSeleccionar(a)) return;
    if (seleccionados[pasajeroActual] === a.id) return;

    const boletoId        = boletosUsuario[pasajeroActual]?.boletoId;
    const asientoAnterior = seleccionados[pasajeroActual];
    if (!boletoId) return;

    guardando = true; errorGuardar = null;
    try {
      const res = await fetch(`${API}/api/asientos/${boletoId}`, {
        method: 'PUT', credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ nuevoAsiento: a.id })
      });
      if (!res.ok) { const e = await res.json(); throw new Error(e.message ?? 'Error al cambiar asiento.'); }

      // Actualizar mapa local sin recargar
      if (asientoAnterior && asientos[asientoAnterior])
        asientos[asientoAnterior] = { ...asientos[asientoAnterior], estado: 'libre' };
      asientos[a.id] = { ...asientos[a.id], estado: 'propio' };

      seleccionados[pasajeroActual] = a.id;
      seleccionados = [...seleccionados];
      asientos      = { ...asientos };

      // Avanzar al siguiente pasajero sin asiento
      const sig = seleccionados.findIndex((s, i) => i > pasajeroActual && !s);
      if (sig !== -1) pasajeroActual = sig;

    } catch (e) {
      errorGuardar = e.message;
    } finally {
      guardando = false;
    }
  }

  function claseAsiento(a) {
    if (!a) return 'asiento--vacio';
    if (a.estado === 'ocupado') return 'asiento--ocupado';
    if (a.estado === 'propio')  return 'asiento--seleccionado';
    if (claseActual === 'Ejecutiva' && a.clase !== 'Ejecutiva') return 'asiento--clase-incorrecta';
    if (claseActual === 'Turista'   && a.clase !== 'Turista')   return 'asiento--clase-incorrecta';
    return 'asiento--libre';
  }

  $: todoSeleccionado = seleccionados.length === pasajerosTotales && seleccionados.every(Boolean);
  $: progreso         = (seleccionados.filter(Boolean).length / pasajerosTotales) * 100;

  function handleContinuar() {
    if (!todoSeleccionado) return;
    if (!esUltimoGrupo) grupoActualIdx++;
    else navigateTo('carrito');
  }
</script>

<div class="asientos-page">
  <div class="asientos-page__container">

    <div class="asientos-page__header">
      <button class="asientos-page__back"
        on:click={() => grupoActualIdx > 0 ? grupoActualIdx-- : navigateTo('datos-pasajeros')}>
        Volver
      </button>
      <div class="asientos-titulo">
        <h1 class="asientos-titulo__main">Selección de Asientos</h1>
        <p class="asientos-titulo__sub">
          {avionMarca} {avionModelo}
          &nbsp;·&nbsp; Vuelo {numeroVuelo}
          &nbsp;·&nbsp; Clase {claseActual}
          &nbsp;·&nbsp; {pasajerosTotales} pasajero{pasajerosTotales > 1 ? 's' : ''}
          {#if totalGrupos > 1}&nbsp;·&nbsp;<strong>Vuelo {grupoActualIdx + 1} de {totalGrupos}</strong>{/if}
        </p>
      </div>
    </div>

    {#if totalGrupos > 1}
      <div class="vuelos-progreso">
        {#each flightData as grupo, i}
          <div class="vuelos-progreso__item"
            class:vuelos-progreso__item--activo={i === grupoActualIdx}
            class:vuelos-progreso__item--completado={i < grupoActualIdx}>
            <span class="vuelos-progreso__numero">{i + 1}</span>
            <span class="vuelos-progreso__label">Vuelo {grupo.numeroVuelo}</span>
          </div>
          {#if i < totalGrupos - 1}
            <div class="vuelos-progreso__linea"
              class:vuelos-progreso__linea--completada={i < grupoActualIdx}></div>
          {/if}
        {/each}
      </div>
    {/if}

    {#if loading}
      <div class="asientos-estado">Cargando mapa de asientos...</div>
    {:else if error}
      <div class="asientos-estado asientos-estado--error">{error}</div>
    {:else}
      <div class="asientos-page__body">
        <div class="asientos-page__mapa-wrap">

          <div class="avion-nariz">
            <svg viewBox="0 0 220 90" fill="none" xmlns="http://www.w3.org/2000/svg" class="avion-nariz__svg">
              <path d="M110 4 C70 4, 14 30, 10 58 L10 86 L210 86 L210 58 C206 30, 150 4, 110 4Z" fill="#1C1A18" stroke="#B89A7A" stroke-width="1.2"/>
              <path d="M110 14 C78 14, 28 36, 24 60 L24 78 L196 78 L196 60 C192 36, 142 14, 110 14Z" fill="#2c2a24" stroke="#B89A7A" stroke-width="0.6" opacity="0.6"/>
              <ellipse cx="68"  cy="50" rx="8" ry="5" fill="#c9a96e" opacity="0.3"/>
              <ellipse cx="110" cy="44" rx="8" ry="5" fill="#c9a96e" opacity="0.3"/>
              <ellipse cx="152" cy="50" rx="8" ry="5" fill="#c9a96e" opacity="0.3"/>
              <text x="110" y="73" text-anchor="middle" fill="#B89A7A" font-size="9" letter-spacing="3" font-family="inherit">CABINA</text>
            </svg>
          </div>

          <div class="avion-cuerpo">

            <!-- Cabecera columnas: letras A-F -->
            <div class="avion-cols-header">
              <div class="avion-col-label"></div>
              {#each COLS_LABEL as lbl, ci}
                {#if ci === 3}<div class="avion-pasillo"></div>{/if}
                <div class="avion-col-label">{lbl}</div>
              {/each}
            </div>

            <!-- ── Ejecutiva: filas numéricas 1..FILAS_EJECUTIVA, cols A-F ── -->
            <!-- IDs: E-A1, E-B1, E-C1... / E-A2, E-B2, E-C2... -->
            <div class="zona-label zona-label--ejecutiva"><span>Ejecutiva</span></div>
            {#each filasEje as fila}
              <div class="avion-fila avion-fila--ejecutiva">
                <div class="avion-fila__num">{fila}</div>
                {#each COLS_LABEL as col, ci}
                  {#if ci === 3}<div class="avion-pasillo"></div>{/if}
                  {@const a = asientos[idEjecutiva(fila, col)]}
                  <button
                    class="asiento asiento--ejecutiva {claseAsiento(a)}"
                    disabled={guardando || esBloqueado(a)}
                    on:click={() => seleccionarAsiento(a)}
                    title="E-{col}{fila}"
                  >
                    {#if a?.estado === 'propio'}
                      <span class="asiento__num">{indicePasajero(a.id) + 1}</span>
                    {/if}
                  </button>
                {/each}
              </div>
            {/each}

            <div class="zona-separador">
              <div class="zona-separador__line"></div>
              <span class="zona-separador__label">Separador de Cabina</span>
              <div class="zona-separador__line"></div>
            </div>

            <!-- ── Turista: filas numéricas 1..filasT, cols A-F ── -->
            <!-- IDs: A1, B1, C1... / A2, B2, C2... -->
            <div class="zona-label zona-label--turista"><span>Turista</span></div>
            {#each filasT as fila}
              <div class="avion-fila">
                <div class="avion-fila__num">{fila}</div>
                {#each COLS_LABEL as col, ci}
                  {#if ci === 3}<div class="avion-pasillo"></div>{/if}
                  {@const a = asientos[idTurista(fila, col)]}
                  <button
                    class="asiento {claseAsiento(a)}"
                    disabled={guardando || esBloqueado(a)}
                    on:click={() => seleccionarAsiento(a)}
                    title="{col}{fila}"
                  >
                    {#if a?.estado === 'propio'}
                      <span class="asiento__num">{indicePasajero(a.id) + 1}</span>
                    {/if}
                  </button>
                {/each}
              </div>
            {/each}

          </div>

          <div class="avion-cola">
            <svg viewBox="0 0 220 50" fill="none" xmlns="http://www.w3.org/2000/svg" class="avion-cola__svg">
              <path d="M10 0 L210 0 L210 24 C180 44, 140 50, 110 50 C80 50, 40 44, 10 24 Z" fill="#1C1A18" stroke="#B89A7A" stroke-width="1.2"/>
            </svg>
          </div>

        </div>

        <!-- SIDEBAR -->
        <aside class="asientos-sidebar">

          <div class="seleccion-progreso">
            <div class="seleccion-progreso__header">
              <span class="seleccion-progreso__titulo">Pasajeros</span>
              <span class="seleccion-progreso__conteo">{seleccionados.filter(Boolean).length} / {pasajerosTotales}</span>
            </div>
            <div class="seleccion-progreso__barra">
              <div class="seleccion-progreso__fill" style="width: {progreso}%"></div>
            </div>
            {#if guardando}<p class="seleccion-progreso__guardando">Guardando asiento...</p>{/if}
            {#if errorGuardar}<p class="seleccion-progreso__error">{errorGuardar}</p>{/if}
          </div>

          <div class="pasajeros-lista">
            {#each boletosUsuario as _, i}
              <button
                class="pasajero-item"
                class:pasajero-item--activo={i === pasajeroActual && !todoSeleccionado}
                class:pasajero-item--completo={!!seleccionados[i]}
                on:click={() => { pasajeroActual = i; }}
              >
                <div class="pasajero-item__numero">{i + 1}</div>
                <div class="pasajero-item__info">
                  <span class="pasajero-item__label">Pasajero {i + 1}</span>
                  <span class="pasajero-item__asiento">
                    {seleccionados[i] ? `Asiento ${seleccionados[i]}` : 'Sin asignar'}
                  </span>
                </div>
              </button>
            {/each}
          </div>

          <div class="leyenda">
            <h3 class="leyenda__titulo">Leyenda</h3>
            <div class="leyenda__items">
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--libre asiento--muestra"></div>
                <span>Disponible</span>
              </div>
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--seleccionado asiento--muestra"></div>
                <span>Seleccionado</span>
              </div>
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--ocupado asiento--muestra"></div>
                <span>Ocupado</span>
              </div>
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--clase-incorrecta asiento--muestra"></div>
                <span>Otra clase</span>
              </div>
            </div>
          </div>

          <button
            class="asientos-continuar"
            class:asientos-continuar--listo={todoSeleccionado}
            disabled={!todoSeleccionado || guardando}
            on:click={handleContinuar}
          >
            {#if guardando}
              Guardando...
            {:else if !todoSeleccionado}
              {@const faltantes = pasajerosTotales - seleccionados.filter(Boolean).length}
              Selecciona {faltantes} asiento{faltantes !== 1 ? 's' : ''} más
            {:else if !esUltimoGrupo}
              Siguiente vuelo →
            {:else}
              Confirmar Asientos
            {/if}
          </button>

        </aside>
      </div>
    {/if}

  </div>
</div>
