// Agencia de Viajes/Movent/src/views/SeleccionAsientos.vue
<template>
  <div class="page">
    <Encabezado />

    <!-- Overlay de pantalla completa cuando el tiempo de reserva expira -->
    <div v-if="tiempoRestante === 0" class="asi-overlay">
      <div class="asi-overlay__card asi-overlay__card--error">
        <svg viewBox="0 0 24 24" fill="none" stroke="#D40511" stroke-width="1.5" width="52" height="52">
          <circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>
        </svg>
        <h3 class="asi-overlay__titulo">Reserva expirada</h3>
        <p class="asi-overlay__msg">El tiempo para completar la reserva ha vencido.</p>
        <button class="asi-btn asi-btn--yellow" @click="$router.push('/principal')" type="button">
          Realizar nueva búsqueda
        </button>
      </div>
    </div>

    <div class="asi-page">
      <div class="asi-container">

        <!-- Encabezado con info del vuelo activo, número de pasajeros y timer de cuenta regresiva -->
        <div class="asi-header">
          <button class="asi-back" @click="$router.push('/reserva')" type="button">
            ← Datos pasajeros
          </button>
          <div class="asi-titulo">
            <h1 class="asi-titulo__main">Selección de Asientos</h1>
            <p class="asi-titulo__sub" v-if="grupoActual">
              {{ grupoActual.avionMarca }} {{ grupoActual.avionModelo }}
              &nbsp;·&nbsp; Vuelo {{ grupoActual.numeroVuelo }}
              &nbsp;·&nbsp; {{ boletosActuales.length }} pasajero{{ boletosActuales.length > 1 ? 's' : '' }}
              <template v-if="totalGrupos > 1">
                &nbsp;·&nbsp; <strong>Vuelo {{ grupoActualIdx + 1 }} de {{ totalGrupos }}</strong>
              </template>
            </p>
          </div>
          <!-- Timer que cambia de color según el tiempo restante -->
          <div v-if="tiempoRestante > 0" class="asi-timer"
            :class="{
              'asi-timer--warn':    tiempoRestante <= 180 && tiempoRestante > 60,
              'asi-timer--urgente': tiempoRestante <= 60,
            }">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14">
              <circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>
            </svg>
            {{ formatTiempo(tiempoRestante) }}
          </div>
        </div>

        <!-- Barra de progreso de vuelos cuando la reserva incluye más de uno -->
        <div v-if="totalGrupos > 1" class="asi-vuelos-prog">
          <template v-for="(g, i) in flightGroups" :key="i">
            <div class="asi-vuelos-prog__item"
              :class="{
                'asi-vuelos-prog__item--activo':    i === grupoActualIdx,
                'asi-vuelos-prog__item--completo':  i < grupoActualIdx,
              }">
              <span class="asi-vuelos-prog__num">{{ i + 1 }}</span>
              <span class="asi-vuelos-prog__label">{{ g.numeroVuelo }}</span>
            </div>
            <div v-if="i < totalGrupos - 1" class="asi-vuelos-prog__linea"
              :class="{ 'asi-vuelos-prog__linea--completa': i < grupoActualIdx }"></div>
          </template>
        </div>

        <!-- Estados de carga y error mientras se obtiene el mapa de asientos -->
        <div v-if="loading" class="asi-estado">
          <div class="asi-spinner"></div>
          <span>Cargando mapa de asientos...</span>
        </div>
        <div v-else-if="error" class="asi-estado asi-estado--error">
          <svg viewBox="0 0 24 24" fill="none" stroke="#D40511" stroke-width="1.5" width="28" height="28">
            <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
          </svg>
          {{ error }}
          <button class="asi-btn asi-btn--ghost" @click="cargarAsientos" style="margin-top:8px">Reintentar</button>
        </div>

        <!-- Cuerpo principal: mapa del avión + sidebar de pasajeros -->
        <div v-else-if="grupoActual" class="asi-body">

          <!-- Mapa visual del avión con zonas ejecutiva y turista -->
          <div class="asi-mapa-wrap">

            <!-- Nariz del avión (decorativa) -->
            <div class="asi-avion-nariz">
              <svg viewBox="0 0 220 90" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M110 4 C70 4, 14 30, 10 58 L10 86 L210 86 L210 58 C206 30, 150 4, 110 4Z"
                  fill="#1C1A18" stroke="#c9a96e" stroke-width="1.2"/>
                <path d="M110 14 C78 14, 28 36, 24 60 L24 78 L196 78 L196 60 C192 36, 142 14, 110 14Z"
                  fill="#2c2a24" stroke="#c9a96e" stroke-width="0.6" opacity="0.6"/>
                <ellipse cx="68"  cy="50" rx="8" ry="5" fill="#FFCC00" opacity="0.25"/>
                <ellipse cx="110" cy="44" rx="8" ry="5" fill="#FFCC00" opacity="0.25"/>
                <ellipse cx="152" cy="50" rx="8" ry="5" fill="#FFCC00" opacity="0.25"/>
                <text x="110" y="73" text-anchor="middle" fill="#c9a96e"
                  font-size="9" letter-spacing="3" font-family="inherit">CABINA</text>
              </svg>
            </div>

            <!-- Cuerpo del avión con filas de asientos -->
            <div class="asi-avion-cuerpo">

              <!-- Cabecera con letras de columna (A-F) -->
              <div class="asi-cols-header">
                <div class="asi-fila-num"></div>
                <template v-for="(lbl, ci) in COLS_LABEL" :key="ci">
                  <div v-if="ci === 3" class="asi-pasillo"></div>
                  <div class="asi-col-lbl">{{ lbl }}</div>
                </template>
              </div>

              <!-- Zona Ejecutiva: filas delanteras -->
              <div class="asi-zona-lbl asi-zona-lbl--eje"><span>Ejecutiva</span></div>
              <div v-for="fila in filasEjeActuales" :key="'eje-'+fila" class="asi-fila asi-fila--eje">
                <div class="asi-fila-num">{{ fila }}</div>
                <template v-for="(colLetter, ci) in COLS_LABEL" :key="ci">
                  <div v-if="ci === 3" class="asi-pasillo"></div>
                  <button
                    :class="['asi-seat', 'asi-seat--eje', claseAsiento(asientos[idEje(fila, colLetter)])]"
                    :disabled="guardando || esBloqueado(asientos[idEje(fila, colLetter)])"
                    @click="seleccionarAsiento(asientos[idEje(fila, colLetter)])"
                    :title="`E-${colLetter}${fila}`"
                    type="button"
                  >
                    <span v-if="asientos[idEje(fila, colLetter)]?.estado === 'propio'" class="asi-seat__num">
                      {{ indicePasajero(idEje(fila, colLetter)) + 1 }}
                    </span>
                  </button>
                </template>
              </div>

              <!-- Separador visual entre cabina ejecutiva y turista -->
              <div class="asi-separador">
                <div class="asi-separador__linea"></div>
                <span class="asi-separador__lbl">Separador de Cabina</span>
                <div class="asi-separador__linea"></div>
              </div>

              <!-- Zona Turista: filas traseras -->
              <div class="asi-zona-lbl asi-zona-lbl--tur"><span>Turista</span></div>
              <div v-for="fila in filasTActuales" :key="'tur-'+fila" class="asi-fila">
                <div class="asi-fila-num">{{ fila }}</div>
                <template v-for="(colLetter, ci) in COLS_LABEL" :key="ci">
                  <div v-if="ci === 3" class="asi-pasillo"></div>
                  <button
                    :class="['asi-seat', claseAsiento(asientos[idTur(fila, colLetter)])]"
                    :disabled="guardando || esBloqueado(asientos[idTur(fila, colLetter)])"
                    @click="seleccionarAsiento(asientos[idTur(fila, colLetter)])"
                    :title="`${colLetter}${fila}`"
                    type="button"
                  >
                    <span v-if="asientos[idTur(fila, colLetter)]?.estado === 'propio'" class="asi-seat__num">
                      {{ indicePasajero(idTur(fila, colLetter)) + 1 }}
                    </span>
                  </button>
                </template>
              </div>

            </div><!-- /avion-cuerpo -->

            <!-- Cola del avión (decorativa) -->
            <div class="asi-avion-cola">
              <svg viewBox="0 0 220 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 0 L210 0 L210 24 C180 44, 140 50, 110 50 C80 50, 40 44, 10 24 Z"
                  fill="#1C1A18" stroke="#c9a96e" stroke-width="1.2"/>
              </svg>
            </div>

          </div><!-- /mapa-wrap -->

          <!-- Sidebar derecho: progreso, lista de pasajeros, leyenda y botón continuar -->
          <aside class="asi-sidebar">

            <!-- Barra de progreso indicando cuántos asientos han sido asignados -->
            <div class="asi-progreso">
              <div class="asi-progreso__header">
                <span class="asi-progreso__titulo">Pasajeros</span>
                <span class="asi-progreso__conteo">
                  {{ seleccionados.filter(Boolean).length }} / {{ boletosActuales.length }}
                </span>
              </div>
              <div class="asi-progreso__barra">
                <div class="asi-progreso__fill" :style="{ width: progreso + '%' }"></div>
              </div>
              <p v-if="guardando" class="asi-progreso__guardando">
                <span class="asi-spinner-sm"></span> Guardando asiento...
              </p>
              <p v-if="errorGuardar" class="asi-progreso__error">{{ errorGuardar }}</p>
            </div>

            <!-- Lista de pasajeros con su asiento actual y clase -->
            <div class="asi-pax-lista">
              <div v-for="(b, i) in boletosActuales" :key="b.boletoId"
                class="asi-pax-item"
                :class="{
                  'asi-pax-item--activo':   i === pasajeroActual && !todoSeleccionado,
                  'asi-pax-item--completo': !!seleccionados[i],
                }"
                @click="pasajeroActual = i"
                role="button" tabindex="0">
                <div class="asi-pax-item__num">{{ i + 1 }}</div>
                <div class="asi-pax-item__info">
                  <span class="asi-pax-item__label">Pasajero {{ i + 1 }}</span>
                  <span class="asi-pax-item__asiento">
                    {{ seleccionados[i] ? `Asiento ${seleccionados[i]}` : 'Sin asignar' }}
                  </span>
                  <span class="asi-pax-item__clase">{{ b.claseId === 2 ? 'Ejecutiva' : 'Turista' }}</span>
                </div>
              </div>
            </div>

            <!-- Leyenda visual de los estados posibles de un asiento -->
            <div class="asi-leyenda">
              <h3 class="asi-leyenda__titulo">Leyenda</h3>
              <div class="asi-leyenda__items">
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--libre asi-seat--muestra"></div>
                  <span>Disponible</span>
                </div>
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--seleccionado asi-seat--muestra"></div>
                  <span>Tuyo</span>
                </div>
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--ocupado asi-seat--muestra"></div>
                  <span>Ocupado</span>
                </div>
                <div class="asi-leyenda__item">
                  <div class="asi-seat asi-seat--bloqueado asi-seat--muestra"></div>
                  <span>Otra clase</span>
                </div>
              </div>
            </div>

            <!-- Botón de continuar: avanza al siguiente vuelo o confirma todos los asientos -->
            <button class="asi-continuar"
              :class="{ 'asi-continuar--listo': todoSeleccionado && !guardando }"
              :disabled="!todoSeleccionado || guardando"
              @click="handleContinuar"
              type="button">
              <template v-if="guardando">Guardando...</template>
              <template v-else-if="!todoSeleccionado">
                Selecciona {{ boletosActuales.length - seleccionados.filter(Boolean).length }}
                asiento{{ (boletosActuales.length - seleccionados.filter(Boolean).length) !== 1 ? 's' : '' }} más
              </template>
              <template v-else-if="!esUltimoGrupo">Siguiente vuelo →</template>
              <template v-else>Confirmar Asientos ✓</template>
            </button>

          </aside>
        </div><!-- /body -->

      </div>
    </div>

    <Piepagina />
  </div>
</template>

<script setup>
/**
 * @file Seleccionasientos.vue
 * @description Vista interactiva para que los pasajeros elijan sus asientos en el mapa
 * del avión. Soporta múltiples vuelos (grupos), clases ejecutiva y turista, timer de
 * expiración de reserva y sincronización en tiempo real con el backend.
 */
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter, onBeforeRouteLeave } from 'vue-router'
import Encabezado from '../components/Encabezado.vue'
import Piepagina from '../components/Piepagina.vue'
import '../styles/Seleccionasientos.css'

const router = useRouter()

/** URL base del backend. @type {string} */
const API = import.meta.env.VITE_API_URL || 'http://localhost:8080'

/** Etiquetas de columna para el mapa de asientos (A-F). @type {string[]} */
const COLS_LABEL = ['A','B','C','D','E','F']

/** Segundos restantes en el contador regresivo de la reserva. @type {import('vue').Ref<number>} */
const tiempoRestante = ref(0)

/** Total de segundos con que se inició el timer (para animaciones de barra si se necesitara). @type {import('vue').Ref<number>} */
const tiempoTotal = ref(600)

/** Referencia al intervalo del timer para poder limpiarlo al desmontar. @type {import('vue').Ref<number|null>} */
const timerInterval = ref(null)

/**
 * Formatea segundos a string MM:SS.
 * @param {number} s - segundos totales
 * @returns {string}
 */
function formatTiempo(s) {
  return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`
}

/**
 * Inicia o reinicia el contador regresivo con la cantidad de segundos indicada.
 * @param {number} segs - segundos totales para la cuenta regresiva
 */
function iniciarTimer(segs) {
  tiempoRestante.value = segs
  tiempoTotal.value    = segs
  if (timerInterval.value) clearInterval(timerInterval.value)
  timerInterval.value = setInterval(() => {
    tiempoRestante.value = Math.max(0, tiempoRestante.value - 1)
    if (tiempoRestante.value === 0) clearInterval(timerInterval.value)
  }, 1000)
}

onUnmounted(() => { if (timerInterval.value) clearInterval(timerInterval.value) })

/** ID de la reservación en curso. @type {import('vue').Ref<number|null>} */
const reservacionId = ref(null)

/** ID del proveedor de la reservación. @type {import('vue').Ref<number|null>} */
const proveedorId = ref(null)

/** Grupos de vuelos devueltos por la API, cada uno con su propio mapa de asientos. @type {import('vue').Ref<any[]>} */
const flightGroups = ref([])

/** Índice del grupo (vuelo) que se está procesando actualmente. @type {import('vue').Ref<number>} */
const grupoActualIdx = ref(0)

/** Indica si la carga inicial de asientos está en curso. @type {import('vue').Ref<boolean>} */
const loading = ref(true)

/** Mensaje de error de carga o de API. @type {import('vue').Ref<string|null>} */
const error = ref(null)

/** Indica si se está guardando la elección de un asiento en el backend. @type {import('vue').Ref<boolean>} */
const guardando = ref(false)

/** Mensaje de error cuando falla el guardado de un asiento. @type {import('vue').Ref<string|null>} */
const errorGuardar = ref(null)

/**
 * Mapa plano de todos los asientos del vuelo actual.
 * Clave: ID del asiento (ej. "A3" o "E-B2"), valor: objeto con estado, clase, fila y columna.
 * @type {import('vue').Ref<Record<string, {id: string, fila: number, col: string, clase: string, estado: string}>>}
 */
const asientos = ref({})

/**
 * Array de IDs de asiento seleccionados, indexado por posición de pasajero.
 * null significa que ese pasajero aún no tiene asiento.
 * @type {import('vue').Ref<(string|null)[]>}
 */
const seleccionados = ref([])

/** Índice del pasajero activo al que se le asignará el próximo asiento que se clickee. @type {import('vue').Ref<number>} */
const pasajeroActual = ref(0)

/** Grupo de vuelo actualmente en pantalla. @type {import('vue').ComputedRef<any|null>} */
const grupoActual = computed(() => flightGroups.value[grupoActualIdx.value] ?? null)

/** Cantidad total de grupos (vuelos) en la reserva. @type {import('vue').ComputedRef<number>} */
const totalGrupos = computed(() => flightGroups.value.length)

/** True si el grupo actual es el último vuelo de la reserva. @type {import('vue').ComputedRef<boolean>} */
const esUltimoGrupo = computed(() => grupoActualIdx.value === totalGrupos.value - 1)

/** Boletos del grupo actual, uno por pasajero. @type {import('vue').ComputedRef<any[]>} */
const boletosActuales = computed(() => grupoActual.value?.boletosAgencia ?? [])

/**
 * Clase (Ejecutiva o Turista) del pasajero actualmente seleccionado.
 * Determina qué zona del avión puede usar.
 * @type {import('vue').ComputedRef<string>}
 */
const claseActual = computed(() => {
  const b = boletosActuales.value[pasajeroActual.value]
  return b?.claseId === 2 ? 'Ejecutiva' : 'Turista'
})

/** Números de fila de la zona ejecutiva del vuelo actual. @type {import('vue').ComputedRef<number[]>} */
const filasEjeActuales = computed(() => {
  const g = grupoActual.value
  if (!g) return []
  return Array.from({ length: g.filasEjecutiva }, (_, i) => i + 1)
})

/** Números de fila de la zona turista del vuelo actual. @type {import('vue').ComputedRef<number[]>} */
const filasTActuales = computed(() => {
  const g = grupoActual.value
  if (!g) return []
  return Array.from({ length: g.totalFilas - g.filasEjecutiva }, (_, i) => i + 1)
})

/** Porcentaje de asientos completados respecto al total de pasajeros. @type {import('vue').ComputedRef<number>} */
const progreso = computed(() => {
  const n = boletosActuales.value.length
  if (!n) return 0
  return (seleccionados.value.filter(Boolean).length / n) * 100
})

/** True cuando todos los pasajeros tienen asiento asignado. @type {import('vue').ComputedRef<boolean>} */
const todoSeleccionado = computed(() =>
  boletosActuales.value.length > 0 &&
  seleccionados.value.length === boletosActuales.value.length &&
  seleccionados.value.every(Boolean)
)

/**
 * Generador de letras para etiquetas de columna (A, B, ..., Z, AA, AB...).
 * @param {number} cantidad - cuántas letras generar
 * @yields {string}
 */
function* generarLetras(cantidad) {
  const abc = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  for (let i = 0; i < cantidad; i++) {
    let s = '', n = i
    do { s = abc[n % 26] + s; n = Math.floor(n / 26) - 1 } while (n >= 0)
    yield s
  }
}

/**
 * Genera el ID de un asiento de zona ejecutiva.
 * @param {number} rowNum - número de fila
 * @param {string} colLetter - letra de columna
 * @returns {string} ej. "E-B3"
 */
function idEje(rowNum, colLetter) { return `E-${colLetter}${rowNum}` }

/**
 * Genera el ID de un asiento de zona turista.
 * @param {number} rowNum - número de fila
 * @param {string} colLetter - letra de columna
 * @returns {string} ej. "B3"
 */
function idTur(rowNum, colLetter) { return `${colLetter}${rowNum}` }

/**
 * Elimina de sessionStorage todos los datos relacionados al flujo de reserva activo.
 */
function limpiarSesionReserva() {
  sessionStorage.removeItem('checkout_data')
  sessionStorage.removeItem('_reserva_expires_at')
  sessionStorage.removeItem('_reserva_id')
  sessionStorage.removeItem('_reserva_no')
  sessionStorage.removeItem('vuelo_seleccionado')
  sessionStorage.removeItem('hotel_seleccionado')
  sessionStorage.removeItem('paquete_seleccionado')
}

/** Rutas que pertenecen al flujo de reserva; al salir hacia otra se limpia la sesión. @type {string[]} */
const FLUJO_RESERVA = ['/reservar', '/seleccion-asientos', '/checkout', '/confirmacion']

/** Guard de navegación: limpia la sesión si el usuario abandona el flujo de reserva. */
onBeforeRouteLeave((to) => {
  if (!FLUJO_RESERVA.includes(to.path)) {
    limpiarSesionReserva()
  }
})

onMounted(async () => {
  const raw = sessionStorage.getItem('checkout_data')
  if (!raw) { router.push('/principal'); return }

  let cd
  try { cd = JSON.parse(raw) } catch { limpiarSesionReserva(); router.push('/principal'); return }

  if (!cd.reservacionId || !cd.proveedorId) {
    limpiarSesionReserva()
    router.push('/principal')
    return
  }

  reservacionId.value = cd.reservacionId
  proveedorId.value   = cd.proveedorId

  // Restaurar timer desde sessionStorage para que sea consistente entre recargas
  const expAt = sessionStorage.getItem('_reserva_expires_at')
  if (expAt) {
    const segs = Math.floor((Number(expAt) - Date.now()) / 1000)
    if (segs > 0) iniciarTimer(segs)
    else {
      limpiarSesionReserva()
      router.push('/principal')
      return
    }
  }

  await cargarAsientos()
})

/**
 * Carga el mapa de asientos desde el backend para la reservación y proveedor actuales.
 * Llena flightGroups y construye el mapa del primer vuelo.
 */
async function cargarAsientos() {
  loading.value = true; error.value = null

  try {
    const res = await fetch(`${API}/api/reservaciones/asientos-vuelo`, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        reservacion_id: reservacionId.value,
        proveedor_id:   proveedorId.value,
      }),
    })
    if (!res.ok) {
      const e = await res.json().catch(() => ({}))
      throw new Error(e.error ?? `Error ${res.status} al cargar asientos.`)
    }
    flightGroups.value = await res.json()
    if (!flightGroups.value.length) throw new Error('No se recibieron datos de vuelos.')
    construirMapa(0)
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

/**
 * Construye el mapa reactivo de asientos para el grupo (vuelo) indicado.
 * Marca los asientos ocupados, los propios del usuario y los libres.
 * @param {number} idx - índice del grupo en flightGroups
 */
function construirMapa(idx) {
  const grupo = flightGroups.value[idx]
  if (!grupo) return

  const ocupados = new Set(grupo.asientosOcupados ?? [])
  const boletos  = grupo.boletosAgencia ?? []

  seleccionados.value  = boletos.map(b => b.asiento ?? null)
  const primerLibre    = seleccionados.value.findIndex(s => !s)
  pasajeroActual.value = primerLibre === -1 ? 0 : primerLibre

  const mapa = {}
  const cols = ['A','B','C','D','E','F']

  // Zona ejecutiva: E-A1, E-B1, ..., E-F{filasEjecutiva}
  for (let row = 1; row <= grupo.filasEjecutiva; row++) {
    for (const col of cols) {
      const id = idEje(row, col)
      mapa[id] = {
        id, fila: row, col, clase: 'Ejecutiva',
        estado: ocupados.has(id)               ? 'ocupado'
              : seleccionados.value.includes(id) ? 'propio'
              : 'libre',
      }
    }
  }

  // Zona turista: A1, B1, ..., F{filasT}
  const filasT = grupo.totalFilas - grupo.filasEjecutiva
  for (let row = 1; row <= filasT; row++) {
    for (const col of cols) {
      const id = idTur(row, col)
      mapa[id] = {
        id, fila: row, col, clase: 'Turista',
        estado: ocupados.has(id)               ? 'ocupado'
              : seleccionados.value.includes(id) ? 'propio'
              : 'libre',
      }
    }
  }

  asientos.value = mapa
}

/**
 * Determina si un asiento debe estar deshabilitado para el pasajero activo.
 * Un asiento se bloquea si está ocupado, o si pertenece a una clase distinta.
 * @param {object|undefined} a - objeto asiento del mapa
 * @returns {boolean}
 */
function esBloqueado(a) {
  if (!a) return true
  if (a.estado === 'ocupado') return true
  if (a.estado === 'propio')  return false
  if (claseActual.value === 'Ejecutiva' && a.clase !== 'Ejecutiva') return true
  if (claseActual.value === 'Turista'   && a.clase !== 'Turista')   return true
  return false
}

/**
 * Devuelve la clase CSS correspondiente al estado visual del asiento.
 * @param {object|undefined} a - objeto asiento del mapa
 * @returns {string}
 */
function claseAsiento(a) {
  if (!a) return 'asi-seat--vacio'
  if (a.estado === 'ocupado') return 'asi-seat--ocupado'
  if (a.estado === 'propio')  return 'asi-seat--seleccionado'
  const puedePasajeroActual =
    (claseActual.value === 'Ejecutiva' && a.clase === 'Ejecutiva') ||
    (claseActual.value === 'Turista'   && a.clase === 'Turista')
  if (!puedePasajeroActual) return 'asi-seat--bloqueado'
  return 'asi-seat--libre'
}

/**
 * Devuelve el índice del pasajero que tiene asignado el asiento con ese ID.
 * @param {string} id - ID del asiento
 * @returns {number} -1 si no está asignado
 */
function indicePasajero(id) { return seleccionados.value.indexOf(id) }

/**
 * Maneja el click en un asiento: valida clase, llama al backend para guardar
 * el cambio y actualiza el mapa local sin recargar.
 * @param {object|undefined} a - objeto asiento del mapa
 */
async function seleccionarAsiento(a) {
  if (guardando.value || !a || a.estado === 'ocupado') return

  // Click en asiento propio: solo cambiar el foco al pasajero que lo tiene
  if (a.estado === 'propio') {
    const idx = seleccionados.value.indexOf(a.id)
    if (idx !== -1) pasajeroActual.value = idx
    return
  }

  if (claseActual.value === 'Ejecutiva' && a.clase !== 'Ejecutiva') return
  if (claseActual.value === 'Turista'   && a.clase !== 'Turista')   return
  if (seleccionados.value[pasajeroActual.value] === a.id) return

  const boleto         = boletosActuales.value[pasajeroActual.value]
  const asientoAnterior = seleccionados.value[pasajeroActual.value]
  if (!boleto) return

  guardando.value = true; errorGuardar.value = null

  try {
    const res = await fetch(`${API}/api/reservaciones/asientos-vuelo`, {
      method: 'PUT',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        reservacion_id: reservacionId.value,
        proveedor_id:   proveedorId.value,
        boleto_id:      boleto.boletoId,
        nuevo_asiento:  a.id,
      }),
    })
    if (!res.ok) {
      const e = await res.json().catch(() => ({}))
      throw new Error(e.error ?? 'Error al cambiar asiento.')
    }

    // Actualizar mapa local optimistamente sin recargar toda la lista
    const nuevoMapa = { ...asientos.value }
    if (asientoAnterior && nuevoMapa[asientoAnterior]) {
      nuevoMapa[asientoAnterior] = { ...nuevoMapa[asientoAnterior], estado: 'libre' }
    }
    nuevoMapa[a.id] = { ...nuevoMapa[a.id], estado: 'propio' }
    asientos.value  = nuevoMapa

    const nuevaSel = [...seleccionados.value]
    nuevaSel[pasajeroActual.value] = a.id
    seleccionados.value = nuevaSel

    // Avanzar automáticamente al siguiente pasajero sin asiento
    const sig = nuevaSel.findIndex((s, i) => i > pasajeroActual.value && !s)
    if (sig !== -1) pasajeroActual.value = sig

  } catch (e) {
    errorGuardar.value = e.message
  } finally {
    guardando.value = false
  }
}

/**
 * Avanza al siguiente vuelo o navega al checkout si ya se completó el último.
 * Limpia el timer cuando se confirman todos los asientos.
 */
function handleContinuar() {
  if (!todoSeleccionado.value || guardando.value) return

  if (!esUltimoGrupo.value) {
    grupoActualIdx.value++
    construirMapa(grupoActualIdx.value)
  } else {
    if (timerInterval.value) clearInterval(timerInterval.value)
    sessionStorage.removeItem('_reserva_expires_at')
    sessionStorage.removeItem('_reserva_id')
    sessionStorage.removeItem('_reserva_no')
    router.push('/checkout')
  }
}
</script>

// Aero Linea/AirLine Broom/src/pages/Seleccionasientos.svelte
<script>
/**
 * @file Seleccionasientos.svelte
 * @description Pagina interactiva de mapa de asientos para seleccionar asientos en uno o varios
 * grupos de vuelo. El avion se renderiza visualmente con un SVG de nariz, un cuerpo de cabina
 * dividido en una seccion Ejecutiva (4 filas fijas, columnas A-F, IDs: E-{col}{fila}) y una
 * seccion Turista (filas dinamicas, IDs: {col}{fila}), y un SVG de cola. Al montar, carga el
 * mapa de asientos desde GET /api/asientos/:vueloId y construye un mapa local indexado por
 * IDs de asientos del backend. Cuando el usuario hace clic en un asiento libre, llama a
 * PUT /api/asientos/:boletoId para persistir la asignacion y actualiza el estado local sin
 * recargar. Un panel lateral muestra el progreso de asignacion de pasajeros, una leyenda de
 * asientos y un boton de continuar que avanza al siguiente grupo de vuelo o navega a 'carrito'
 * cuando todos los grupos estan completos.
 */
// @ts-nocheck
  import '../styles/asientos.css';
  import { onMount } from 'svelte';

  /** Funcion para navegar entre las paginas de la aplicacion. @type {function} */
  export let navigateTo;

  /** Arreglo de objetos de grupo de vuelo pasado desde el paso anterior, cada uno con vueloId, numeroVuelo, avionModelo, avionMarca, clase y arreglo de boletos. @type {Array<object>} */
  export let flightData = [];

  import { API } from '../lib/api.js';

  /** Cantidad de columnas de asientos en las zonas Ejecutiva y Turista. @type {number} */
  const NUM_COLUMNAS    = 6;

  /** Cantidad fija de filas en la zona Ejecutiva. @type {number} */
  const FILAS_EJECUTIVA = 4;

  /** Etiquetas de letras de columna usadas como identificadores de columnas de asiento. @type {string[]} */
  const COLS_LABEL      = ['A','B','C','D','E','F'];

  /** Indice del grupo de vuelo activo actualmente siendo mapeado. @type {number} */
  let grupoActualIdx = 0;

  // Objeto del grupo de vuelo actual resuelto desde flightData en grupoActualIdx.
  $: grupoActual   = flightData?.[grupoActualIdx] ?? null;

  // Cantidad total de grupos de vuelo en flightData.
  $: totalGrupos   = flightData?.length ?? 0;

  // Verdadero cuando grupoActualIdx apunta al ultimo grupo de vuelo.
  $: esUltimoGrupo = grupoActualIdx === totalGrupos - 1;

  // ID de vuelo del grupo actual, o null si no esta disponible.
  $: vueloId          = grupoActual?.vueloId      ?? null;

  // Cadena de numero de vuelo para el encabezado de display del grupo actual.
  $: numeroVuelo      = grupoActual?.numeroVuelo   ?? '';

  // Nombre del modelo de avion para el encabezado de display del grupo actual.
  $: avionModelo      = grupoActual?.avionModelo   ?? '';

  // Nombre de la marca del avion para el encabezado de display del grupo actual.
  $: avionMarca       = grupoActual?.avionMarca    ?? '';

  // Clase de asiento del grupo actual ('Turista' o 'Ejecutiva'), restringe los asientos seleccionables.
  $: claseActual      = grupoActual?.clase         ?? 'Turista';

  // Cantidad total de pasajeros (boletos) en el grupo actual.
  $: pasajerosTotales = grupoActual?.boletos?.length ?? 1;

  /** Verdadero mientras la solicitud de la API del mapa de asientos esta en progreso. @type {boolean} */
  let loading      = true;

  /** Mensaje de error mostrado si el mapa de asientos no puede cargarse. @type {string|null} */
  let error        = null;

  /** Verdadero mientras una solicitud PUT de asignacion de asiento esta en progreso. @type {boolean} */
  let guardando    = false;

  /** Mensaje de error mostrado si una solicitud PUT de asignacion de asiento falla. @type {string|null} */
  let errorGuardar = null;

  /** Cantidad total de filas (Ejecutiva + Turista) para el avion del vuelo actual. @type {number} */
  let totalFilas       = 0;

  /** Conjunto de cadenas de ID de asiento ya ocupados por otros pasajeros. @type {Set<string>} */
  let asientosOcupados = new Set();

  /** Arreglo de objetos de boleto con boletoId y asiento para la reservacion del usuario actual. @type {Array<{boletoId: number, asiento: string}>} */
  let boletosUsuario   = [];

  /** Mapa de cadena de ID de asiento a objeto de asiento con id, fila, col, clase y estado. @type {Object.<string, object>} */
  let asientos         = {};

  /** Arreglo de cadenas de ID de asiento, una por pasajero, representando las asignaciones de asiento actuales. @type {string[]} */
  let seleccionados    = [];

  /** Indice del pasajero cuyo asiento se esta asignando actualmente. @type {number} */
  let pasajeroActual   = 0;

  /**
   * Construye la cadena de ID de asiento del backend para un asiento Ejecutiva dado el numero de fila y la letra de columna.
   * @param {number} fila - Numero de fila (base 1).
   * @param {string} col - Letra de columna (A-F).
   * @returns {string} ID de asiento en el formato 'E-{col}{fila}', por ejemplo 'E-A1'.
   */
  function idEjecutiva(fila, col) { return `E-${col}${fila}`; }

  /**
   * Construye la cadena de ID de asiento del backend para un asiento Turista dado el numero de fila y la letra de columna.
   * @param {number} fila - Numero de fila (base 1).
   * @param {string} col - Letra de columna (A-F).
   * @returns {string} ID de asiento en el formato '{col}{fila}', por ejemplo 'A1'.
   */
  function idTurista(fila, col)   { return `${col}${fila}`;   }

  // Arreglo de numeros de fila para la zona Ejecutiva, siempre [1, 2, 3, 4].
  $: filasEje = Array.from({ length: FILAS_EJECUTIVA }, (_, i) => i + 1);

  // Arreglo de numeros de fila para la zona Turista, dimensionado dinamicamente desde totalFilas menos filas Ejecutiva.
  $: filasT = totalFilas > FILAS_EJECUTIVA
      ? Array.from({ length: totalFilas - FILAS_EJECUTIVA }, (_, i) => i + 1)
      : [];

  onMount(async () => {
    if (!flightData || flightData.length === 0) {
      error = 'No se recibio informacion de vuelos.';
      loading = false;
      return;
    }
    await cargarAsientos();
  });

  /** Rastrea el ultimo grupoActualIdx para el que se cargaron asientos para evitar recargas redundantes. @type {number} */
  let ultimoGrupoIdx = -1;

  // Recarga el mapa de asientos cada vez que el indice del grupo activo cambia y hay un vueloId valido.
  $: if (grupoActualIdx !== ultimoGrupoIdx && vueloId) {
    ultimoGrupoIdx = grupoActualIdx;
    cargarAsientos();
  }

  /**
   * Obtiene la disponibilidad de asientos para el vueloId actual desde GET /api/asientos/:vueloId.
   * Llena totalFilas, asientosOcupados, boletosUsuario y seleccionados desde la respuesta, restablece
   * pasajeroActual a 0 y reconstruye el mapa de asientos mediante construirMapa.
   * @async
   * @returns {Promise<void>}
   */
  async function cargarAsientos() {
    if (!vueloId) return;
    loading = true; error = null; errorGuardar = null;
    try {
      const res = await fetch(`${API}/api/asientos/${vueloId}`, { credentials: 'include' });
      if (!res.ok) { const e = await res.json(); throw new Error(e.message ?? 'Error al cargar asientos.'); }
      const data = await res.json();

      totalFilas       = data.totalFilas;
      asientosOcupados = new Set(data.asientosOcupados ?? []);
      boletosUsuario   = data.boletosUsuario ?? [];
      seleccionados    = boletosUsuario.map(b => b.asiento);
      pasajeroActual   = 0;
      construirMapa(data.totalFilas);
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  /**
   * Construye el mapa de asientos indexado por ID de asiento del backend para las zonas Ejecutiva y Turista.
   * Cada entrada tiene id, fila, col, clase y estado ('ocupado', 'propio' o 'libre').
   * @param {number} totalF - Cantidad total de filas del avion (filas Ejecutiva + Turista combinadas).
   */
  function construirMapa(totalF) {
    const mapa = {};
    const filasT = totalF - FILAS_EJECUTIVA;

    for (let row = 1; row <= FILAS_EJECUTIVA; row++) {
      for (const col of COLS_LABEL) {
        const id = idEjecutiva(row, col);
        mapa[id] = {
          id, fila: row, col,
          clase: 'Ejecutiva',
          estado: asientosOcupados.has(id) ? 'ocupado'
                : seleccionados.includes(id) ? 'propio'
                : 'libre'
        };
      }
    }

    for (let row = 1; row <= filasT; row++) {
      for (const col of COLS_LABEL) {
        const id = idTurista(row, col);
        mapa[id] = {
          id, fila: row, col,
          clase: 'Turista',
          estado: asientosOcupados.has(id) ? 'ocupado'
                : seleccionados.includes(id) ? 'propio'
                : 'libre'
        };
      }
    }

    asientos = mapa;
  }

  /**
   * Retorna verdadero si el objeto de asiento dado puede ser seleccionado por el pasajero actual. Un asiento
   * es seleccionable cuando existe, no esta ocupado y pertenece a la misma clase que claseActual.
   * @param {object} a - Objeto de asiento del mapa de asientos.
   * @returns {boolean} Si el asiento puede ser seleccionado.
   */
  function puedeSeleccionar(a) {
    if (!a) return false;
    if (a.estado === 'ocupado') return false;
    if (claseActual === 'Ejecutiva' && a.clase !== 'Ejecutiva') return false;
    if (claseActual === 'Turista'   && a.clase !== 'Turista')   return false;
    return true;
  }

  /**
   * Retorna verdadero si el boton de asiento debe estar deshabilitado. Un asiento esta bloqueado si es null, esta
   * ocupado o pertenece a una clase diferente a claseActual. Los asientos con estado 'propio' nunca se bloquean
   * para que el usuario pueda hacer clic en ellos para cambiar el foco de pasajero.
   * @param {object} a - Objeto de asiento del mapa de asientos.
   * @returns {boolean} Si el boton de asiento debe renderizarse como deshabilitado.
   */
  function esBloqueado(a) {
    if (!a) return true;
    if (a.estado === 'ocupado') return true;
    if (a.estado === 'propio')  return false;
    if (claseActual === 'Ejecutiva' && a.clase !== 'Ejecutiva') return true;
    if (claseActual === 'Turista'   && a.clase !== 'Turista')   return true;
    return false;
  }

  /**
   * Retorna el indice del ID de asiento dado en el arreglo seleccionados, o -1 si no se encuentra.
   * Usado para renderizar el badge de numero de pasajero en asientos ya asignados.
   * @param {string} id - Cadena de ID de asiento a buscar.
   * @returns {number} Indice en seleccionados, o -1.
   */
  function indicePasajero(id) { return seleccionados.indexOf(id); }

  /**
   * Maneja el clic en un boton de asiento. Si el asiento ya pertenece al usuario, desplaza pasajeroActual
   * al indice de ese pasajero. De lo contrario, valida la seleccionabilidad, envia PUT /api/asientos/:boletoId
   * para actualizar la asignacion, actualiza el mapa local de asientos y el arreglo seleccionados sin
   * recargar, y avanza pasajeroActual al siguiente pasajero sin asiento asignado.
   * @async
   * @param {object} a - Objeto de asiento del mapa de asientos.
   * @returns {Promise<void>}
   */
  async function seleccionarAsiento(a) {
    if (guardando || !a || a.estado === 'ocupado') return;

    if (a.estado === 'propio') {
      const idx = seleccionados.indexOf(a.id);
      if (idx !== -1) pasajeroActual = idx;
      return;
    }

    if (!puedeSeleccionar(a)) return;
    if (seleccionados[pasajeroActual] === a.id) return;

    const boletoId        = boletosUsuario[pasajeroActual]?.boletoId;
    const asientoAnterior = seleccionados[pasajeroActual];
    if (!boletoId) return;

    guardando = true; errorGuardar = null;
    try {
      const res = await fetch(`${API}/api/asientos/${boletoId}`, {
        method: 'PUT', credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ nuevoAsiento: a.id })
      });
      if (!res.ok) { const e = await res.json(); throw new Error(e.message ?? 'Error al cambiar asiento.'); }

      if (asientoAnterior && asientos[asientoAnterior])
        asientos[asientoAnterior] = { ...asientos[asientoAnterior], estado: 'libre' };
      asientos[a.id] = { ...asientos[a.id], estado: 'propio' };

      seleccionados[pasajeroActual] = a.id;
      seleccionados = [...seleccionados];
      asientos      = { ...asientos };

      const sig = seleccionados.findIndex((s, i) => i > pasajeroActual && !s);
      if (sig !== -1) pasajeroActual = sig;

    } catch (e) {
      errorGuardar = e.message;
    } finally {
      guardando = false;
    }
  }

  /**
   * Retorna la cadena de clase CSS para un boton de asiento segun su estado y compatibilidad de clase.
   * Valores de retorno posibles: 'asiento--vacio', 'asiento--ocupado', 'asiento--seleccionado',
   * 'asiento--clase-incorrecta' o 'asiento--libre'.
   * @param {object} a - Objeto de asiento del mapa de asientos, o null/undefined.
   * @returns {string} Cadena de clase CSS modificadora.
   */
  function claseAsiento(a) {
    if (!a) return 'asiento--vacio';
    if (a.estado === 'ocupado') return 'asiento--ocupado';
    if (a.estado === 'propio')  return 'asiento--seleccionado';
    if (claseActual === 'Ejecutiva' && a.clase !== 'Ejecutiva') return 'asiento--clase-incorrecta';
    if (claseActual === 'Turista'   && a.clase !== 'Turista')   return 'asiento--clase-incorrecta';
    return 'asiento--libre';
  }

  // Verdadero cuando todos los pasajeros del grupo actual tienen un asiento asignado.
  $: todoSeleccionado = seleccionados.length === pasajerosTotales && seleccionados.every(Boolean);

  // Porcentaje de asientos asignados sobre el total de pasajeros para la barra de progreso.
  $: progreso         = (seleccionados.filter(Boolean).length / pasajerosTotales) * 100;

  /**
   * Avanza al siguiente grupo de vuelo si no esta en el ultimo, o navega a 'carrito' cuando
   * todos los grupos de vuelo han sido mapeados. No hace nada si no todos los asientos estan seleccionados.
   */
  function handleContinuar() {
    if (!todoSeleccionado) return;
    if (!esUltimoGrupo) grupoActualIdx++;
    else navigateTo('carrito');
  }
</script>

<!-- Contenedor principal de la pagina de seleccion de asientos -->
<div class="asientos-page">
  <div class="asientos-page__container">

    <!-- Cabecera con boton de regreso e informacion del vuelo y clase activos -->
    <div class="asientos-page__header">
      <button class="asientos-page__back"
        on:click={() => grupoActualIdx > 0 ? grupoActualIdx-- : navigateTo('datos-pasajeros')}>
        Volver
      </button>
      <div class="asientos-titulo">
        <h1 class="asientos-titulo__main">Seleccion de Asientos</h1>
        <p class="asientos-titulo__sub">
          {avionMarca} {avionModelo}
          &nbsp;·&nbsp; Vuelo {numeroVuelo}
          &nbsp;·&nbsp; Clase {claseActual}
          &nbsp;·&nbsp; {pasajerosTotales} pasajero{pasajerosTotales > 1 ? 's' : ''}
          {#if totalGrupos > 1}&nbsp;·&nbsp;<strong>Vuelo {grupoActualIdx + 1} de {totalGrupos}</strong>{/if}
        </p>
      </div>
    </div>

    <!-- Indicador de progreso por vuelo cuando hay multiples grupos de vuelos -->
    {#if totalGrupos > 1}
      <div class="vuelos-progreso">
        {#each flightData as grupo, i}
          <div class="vuelos-progreso__item"
            class:vuelos-progreso__item--activo={i === grupoActualIdx}
            class:vuelos-progreso__item--completado={i < grupoActualIdx}>
            <span class="vuelos-progreso__numero">{i + 1}</span>
            <span class="vuelos-progreso__label">Vuelo {grupo.numeroVuelo}</span>
          </div>
          {#if i < totalGrupos - 1}
            <div class="vuelos-progreso__linea"
              class:vuelos-progreso__linea--completada={i < grupoActualIdx}></div>
          {/if}
        {/each}
      </div>
    {/if}

    <!-- Estado de carga o error mientras se obtiene el mapa de asientos desde la API -->
    {#if loading}
      <div class="asientos-estado">Cargando mapa de asientos...</div>
    {:else if error}
      <div class="asientos-estado asientos-estado--error">{error}</div>
    {:else}
      <div class="asientos-page__body">
        <div class="asientos-page__mapa-wrap">

          <!-- SVG decorativo de la nariz del avion -->
          <div class="avion-nariz">
            <svg viewBox="0 0 220 90" fill="none" xmlns="http://www.w3.org/2000/svg" class="avion-nariz__svg">
              <path d="M110 4 C70 4, 14 30, 10 58 L10 86 L210 86 L210 58 C206 30, 150 4, 110 4Z" fill="#1C1A18" stroke="#B89A7A" stroke-width="1.2"/>
              <path d="M110 14 C78 14, 28 36, 24 60 L24 78 L196 78 L196 60 C192 36, 142 14, 110 14Z" fill="#2c2a24" stroke="#B89A7A" stroke-width="0.6" opacity="0.6"/>
              <ellipse cx="68"  cy="50" rx="8" ry="5" fill="#c9a96e" opacity="0.3"/>
              <ellipse cx="110" cy="44" rx="8" ry="5" fill="#c9a96e" opacity="0.3"/>
              <ellipse cx="152" cy="50" rx="8" ry="5" fill="#c9a96e" opacity="0.3"/>
              <text x="110" y="73" text-anchor="middle" fill="#B89A7A" font-size="9" letter-spacing="3" font-family="inherit">CABINA</text>
            </svg>
          </div>

          <!-- Cuerpo del avion con encabezado de columnas, zona Ejecutiva y zona Turista -->
          <div class="avion-cuerpo">

            <!-- Etiquetas de columnas A-F con separador de pasillo central -->
            <div class="avion-cols-header">
              <div class="avion-col-label"></div>
              {#each COLS_LABEL as lbl, ci}
                {#if ci === 3}<div class="avion-pasillo"></div>{/if}
                <div class="avion-col-label">{lbl}</div>
              {/each}
            </div>

            <!-- Filas de asientos de la zona Ejecutiva (filas 1 a 4) -->
            <div class="zona-label zona-label--ejecutiva"><span>Ejecutiva</span></div>
            {#each filasEje as fila}
              <div class="avion-fila avion-fila--ejecutiva">
                <div class="avion-fila__num">{fila}</div>
                {#each COLS_LABEL as col, ci}
                  {#if ci === 3}<div class="avion-pasillo"></div>{/if}
                  {@const a = asientos[idEjecutiva(fila, col)]}
                  <button
                    class="asiento asiento--ejecutiva {claseAsiento(a)}"
                    disabled={guardando || esBloqueado(a)}
                    on:click={() => seleccionarAsiento(a)}
                    title="E-{col}{fila}"
                  >
                    {#if a?.estado === 'propio'}
                      <span class="asiento__num">{indicePasajero(a.id) + 1}</span>
                    {/if}
                  </button>
                {/each}
              </div>
            {/each}

            <!-- Separador visual entre la cabina Ejecutiva y la zona Turista -->
            <div class="zona-separador">
              <div class="zona-separador__line"></div>
              <span class="zona-separador__label">Separador de Cabina</span>
              <div class="zona-separador__line"></div>
            </div>

            <!-- Filas de asientos de la zona Turista (filas dinamicas segun el avion) -->
            <div class="zona-label zona-label--turista"><span>Turista</span></div>
            {#each filasT as fila}
              <div class="avion-fila">
                <div class="avion-fila__num">{fila}</div>
                {#each COLS_LABEL as col, ci}
                  {#if ci === 3}<div class="avion-pasillo"></div>{/if}
                  {@const a = asientos[idTurista(fila, col)]}
                  <button
                    class="asiento {claseAsiento(a)}"
                    disabled={guardando || esBloqueado(a)}
                    on:click={() => seleccionarAsiento(a)}
                    title="{col}{fila}"
                  >
                    {#if a?.estado === 'propio'}
                      <span class="asiento__num">{indicePasajero(a.id) + 1}</span>
                    {/if}
                  </button>
                {/each}
              </div>
            {/each}

          </div>

          <!-- SVG decorativo de la cola del avion -->
          <div class="avion-cola">
            <svg viewBox="0 0 220 50" fill="none" xmlns="http://www.w3.org/2000/svg" class="avion-cola__svg">
              <path d="M10 0 L210 0 L210 24 C180 44, 140 50, 110 50 C80 50, 40 44, 10 24 Z" fill="#1C1A18" stroke="#B89A7A" stroke-width="1.2"/>
            </svg>
          </div>

        </div>

        <!-- Panel lateral con progreso de asignacion, lista de pasajeros, leyenda y boton de continuar -->
        <aside class="asientos-sidebar">

          <!-- Barra de progreso de asientos asignados sobre el total de pasajeros -->
          <div class="seleccion-progreso">
            <div class="seleccion-progreso__header">
              <span class="seleccion-progreso__titulo">Pasajeros</span>
              <span class="seleccion-progreso__conteo">{seleccionados.filter(Boolean).length} / {pasajerosTotales}</span>
            </div>
            <div class="seleccion-progreso__barra">
              <div class="seleccion-progreso__fill" style="width: {progreso}%"></div>
            </div>
            {#if guardando}<p class="seleccion-progreso__guardando">Guardando asiento...</p>{/if}
            {#if errorGuardar}<p class="seleccion-progreso__error">{errorGuardar}</p>{/if}
          </div>

          <!-- Lista de pasajeros con estado de asiento asignado o pendiente por cada boleto -->
          <div class="pasajeros-lista">
            {#each boletosUsuario as _, i}
              <button
                class="pasajero-item"
                class:pasajero-item--activo={i === pasajeroActual && !todoSeleccionado}
                class:pasajero-item--completo={!!seleccionados[i]}
                on:click={() => { pasajeroActual = i; }}
              >
                <div class="pasajero-item__numero">{i + 1}</div>
                <div class="pasajero-item__info">
                  <span class="pasajero-item__label">Pasajero {i + 1}</span>
                  <span class="pasajero-item__asiento">
                    {seleccionados[i] ? `Asiento ${seleccionados[i]}` : 'Sin asignar'}
                  </span>
                </div>
              </button>
            {/each}
          </div>

          <!-- Leyenda de colores de los estados posibles de un asiento -->
          <div class="leyenda">
            <h3 class="leyenda__titulo">Leyenda</h3>
            <div class="leyenda__items">
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--libre asiento--muestra"></div>
                <span>Disponible</span>
              </div>
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--seleccionado asiento--muestra"></div>
                <span>Seleccionado</span>
              </div>
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--ocupado asiento--muestra"></div>
                <span>Ocupado</span>
              </div>
              <div class="leyenda__item">
                <div class="leyenda__muestra asiento asiento--clase-incorrecta asiento--muestra"></div>
                <span>Otra clase</span>
              </div>
            </div>
          </div>

          <!-- Boton de avance al siguiente vuelo o confirmacion cuando todos los asientos estan asignados -->
          <button
            class="asientos-continuar"
            class:asientos-continuar--listo={todoSeleccionado}
            disabled={!todoSeleccionado || guardando}
            on:click={handleContinuar}
          >
            {#if guardando}
              Guardando...
            {:else if !todoSeleccionado}
              {@const faltantes = pasajerosTotales - seleccionados.filter(Boolean).length}
              Selecciona {faltantes} asiento{faltantes !== 1 ? 's' : ''} mas
            {:else if !esUltimoGrupo}
              Siguiente vuelo
            {:else}
              Confirmar Asientos
            {/if}
          </button>

        </aside>
      </div>
    {/if}

  </div>
</div>
