// Agencia de Viajes/Movent/src/views/CentroAyuda.vue
<template>
  <div class="page">
    <Encabezado />

    <!-- Hero de la vista con imagen representativa del equipo de ayuda -->
    <section class="info-hero" style="background-image: url('/empleada.png')">
      <div class="info-hero-overlay"></div>
      <div class="info-hero-content">
        <div class="info-hero-icon">
          <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
        </div>
        <p class="info-eyebrow">Movent</p>
        <h1 class="info-hero-title">Centro de Ayuda</h1>
        <p class="info-hero-subtitle">Encuentra respuestas rápidas sobre reservaciones, pagos y más.</p>
      </div>
    </section>

    <div class="info-wrap">
      <!-- Botón para volver a la página de información general -->
      <button class="info-back" @click="$router.push('/informacion')">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>
        Volver a Información
      </button>

      <div class="info-section-body">

        <!-- Tarjeta de temas frecuentes con mini-cards por categoría -->
        <div class="info-card">
          <h2 class="info-section-title">Temas frecuentes</h2>
          <div class="info-cards-grid">

            <!-- Mini-card: gestión de reservaciones -->
            <div class="info-mini-card">
              <div class="info-mini-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
              </div>
              <h3>Mis Reservaciones</h3>
              <p>Consulta, modifica o cancela desde tu perfil usando tu código único #MVT-2026-XXXXXX.</p>
            </div>

            <!-- Mini-card: métodos de pago y comprobantes -->
            <div class="info-mini-card">
              <div class="info-mini-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>
              </div>
              <h3>Pagos y Facturas</h3>
              <p>Aceptamos tarjetas de crédito y débito. Tu voucher PDF se genera al confirmar el pago.</p>
            </div>

            <!-- Mini-card: información sobre escalas y tiempos de vuelo -->
            <div class="info-mini-card">
              <div class="info-mini-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
              </div>
              <h3>Escalas y Tiempos</h3>
              <p>Mostramos vuelos directos y con escalas. Cada tramo incluye aeropuerto y tiempo de conexión.</p>
            </div>

            <!-- Mini-card: política de cancelaciones -->
            <div class="info-mini-card">
              <div class="info-mini-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v6M14 11v6"/></svg>
              </div>
              <h3>Cancelaciones</h3>
              <p>Cancela siguiendo las políticas de cada proveedor desde "Mis Reservaciones".</p>
            </div>

          </div>
        </div>

        <!-- Tarjeta con información de contacto directo -->
        <div class="info-card">
          <h2 class="info-section-title">¿No encontraste lo que buscabas?</h2>
          <p class="info-prose">Nuestro equipo está disponible de lunes a viernes de 8:00 a 18:00.</p>
          <!-- Datos de contacto: teléfono y correo -->
          <div class="info-highlight">
            Llámanos al <strong>+502 5754-5388</strong> o escríbenos a <strong>info@movent.com</strong>
          </div>
        </div>

      </div>
    </div>

    <Piepagina />
  </div>
</template>

<script setup>
/**
 * @file CentroAyuda.vue
 * @description Vista estática del Centro de Ayuda de Movent. Muestra mini-cards
 * con los temas de soporte más frecuentes (reservaciones, pagos, escalas,
 * cancelaciones) y los datos de contacto del equipo de atención al cliente.
 */
import Encabezado from '../components/Encabezado.vue'
import Piepagina from '../components/Piepagina.vue'
import '../styles/informacion.css'
</script>

// Cadena de Hoteles/Miku Inn/src/pages/CentroAyuda.svelte
<script>
  // @ts-nocheck
  import '../styles/info-pages.css';
  export let navigateTo;
</script>

<div class="info-page">
  <div class="info-hero">
    <div class="info-hero__content">
      <div class="info-hero__icon">🛎️</div>
      <p class="info-hero__eyebrow">Miku Inn</p>
      <h1 class="info-hero__title">Centro de Ayuda</h1>
      <p class="info-hero__subtitle">Encuentra respuestas rápidas y soporte para todo lo relacionado con tus reservaciones.</p>
    </div>
  </div>

  <div class="info-container">
    <button class="info-back" on:click={() => navigateTo('home')}>
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>
      Volver al inicio
    </button>

    <div class="info-contact-grid">
      <div class="info-contact-item">
        <div class="info-contact-item__icon">📞</div>
        <div>
          <p class="info-contact-item__label">Atención 24/7</p>
          <p class="info-contact-item__value">+502 4276-8687</p>
          <p class="info-contact-item__sub">Llamadas y WhatsApp</p>
        </div>
      </div>
      <div class="info-contact-item">
        <div class="info-contact-item__icon">✉️</div>
        <div>
          <p class="info-contact-item__label">Email</p>
          <p class="info-contact-item__value">info@mikuinn.com</p>
          <p class="info-contact-item__sub">Respuesta en menos de 24h</p>
        </div>
      </div>
      <div class="info-contact-item">
        <div class="info-contact-item__icon">📍</div>
        <div>
          <p class="info-contact-item__label">Oficina Central</p>
          <p class="info-contact-item__value">Guatemala City</p>
          <p class="info-contact-item__sub">Guatemala</p>
        </div>
      </div>
    </div>

    <div class="info-card">
      <h2 class="info-section-title">Temas de ayuda frecuentes</h2>
      <div class="info-cards-grid">
        <div class="info-card" style="margin:0">
          <span class="info-card__icon">📋</span>
          <h3 class="info-card__title">Mis reservaciones</h3>
          <p class="info-card__text">Consulta, modifica o cancela tus reservaciones desde tu perfil en "Mis Reservaciones".</p>
        </div>
        <div class="info-card" style="margin:0">
          <span class="info-card__icon">💳</span>
          <h3 class="info-card__title">Pagos y facturas</h3>
          <p class="info-card__text">Aceptamos tarjetas de crédito y débito. Tu factura se genera automáticamente al confirmar el pago.</p>
        </div>
        <div class="info-card" style="margin:0">
          <span class="info-card__icon">🔑</span>
          <h3 class="info-card__title">Check-in / Check-out</h3>
          <p class="info-card__text">Consulta los horarios y procedimientos de cada hotel directamente en su página de detalle.</p>
        </div>
        <div class="info-card" style="margin:0">
          <span class="info-card__icon">❌</span>
          <h3 class="info-card__title">Cancelaciones</h3>
          <p class="info-card__text">Puedes cancelar hasta 24 horas antes del check-in. Ver política completa de cancelación.</p>
        </div>
      </div>
    </div>

    <div class="info-card">
      <h2 class="info-section-title">¿No encontraste lo que buscabas?</h2>
      <p class="info-prose">Nuestro equipo de soporte está disponible las 24 horas del día, los 7 días de la semana. Contáctanos por teléfono o escríbenos al correo y te responderemos a la brevedad posible.</p>
      <div class="info-highlight">
        Para consultas urgentes llámanos al <strong>+502 4276-8687</strong> o escríbenos a <strong>info@mikuinn.com</strong>
      </div>
    </div>
  </div>
</div>
