// Aero Linea/AirLine Broom/src/pages/PreguntasFrecuentes.svelte
<script>
  // @ts-nocheck
  import '../styles/info-pages.css';
  export let navigateTo;

  const faqs = [
    {
      q: 'Como realizo una reserva de vuelo?',
      a: 'Desde la pagina principal ingresa tu origen, destino, fecha de salida y cantidad de pasajeros. El sistema mostrara unicamente los vuelos con asientos disponibles. Selecciona el vuelo, elige el tipo de asiento (Economico o Ejecutivo), ingresa los datos de cada pasajero y completa el pago con tu tarjeta. Al confirmar recibiras un codigo unico de reserva y un correo de confirmacion con tu boleto en PDF.'
    },
    {
      q: 'Puedo buscar vuelos de ida y vuelta?',
      a: 'Si. Al momento de buscar puedes seleccionar la opcion de ida y vuelta para indicar tambien la fecha de regreso. El sistema buscara vuelos en ambas direcciones para que puedas reservarlos en una sola transaccion.'
    },
    {
      q: 'Que tipos de asiento ofrece Broom AirLine?',
      a: 'Ofrecemos dos clases: Economico y Ejecutivo. Cada tipo tiene precio diferente claramente visible al momento de seleccionar el vuelo. El sistema muestra las caracteristicas de cada clase y la disponibilidad en tiempo real antes de confirmar la compra.'
    },
    {
      q: 'Puedo comprar boletos para varios pasajeros a la vez?',
      a: 'Si. Puedes seleccionar la cantidad de pasajeros antes de buscar. Para compras grupales el sistema solicita la informacion individual de cada pasajero. El precio total se calcula multiplicando por el numero de pasajeros y todos los boletos del grupo comparten el mismo codigo de reserva.'
    },
    {
      q: 'Como funciona el bloqueo temporal de asientos?',
      a: 'Al iniciar el proceso de compra, el sistema bloquea temporalmente el asiento seleccionado por 10 minutos. Si no completas la compra en ese tiempo, el asiento se libera automaticamente y queda disponible para otros usuarios. Esto evita que dos personas reserven el mismo asiento al mismo tiempo.'
    },
    {
      q: 'Donde encuentro mi codigo de reserva?',
      a: 'Tu codigo unico de reserva (formato alfanumerico tipo #VGT-2026-A7B9C2) se genera automaticamente al confirmar el pago. Lo recibiras por correo electronico junto con el detalle de tu vuelo y el boleto en PDF. Tambien puedes consultarlo desde tu perfil en la seccion Mis Reservas.'
    },
    {
      q: 'Como cancelo una reserva?',
      a: 'Inicia sesion en tu cuenta, ve a Mis Reservas, selecciona la reserva que deseas cancelar y haz clic en Cancelar reserva. El sistema pedira confirmacion antes de procesar. Al cancelar recibiras un correo de confirmacion y los asientos quedaran disponibles de inmediato para otros usuarios.'
    },
    {
      q: 'Como descargo mi boleto en PDF?',
      a: 'Desde la seccion Mis Reservas de tu perfil, selecciona la reserva y encontraras la opcion de descargar el boleto electronico en formato PDF. El boleto tambien se adjunta automaticamente al correo de confirmacion de compra.'
    },
    {
      q: 'Que pasa si un vuelo tiene escalas?',
      a: 'El sistema indica claramente si un vuelo tiene escalas, mostrando cada ciudad de escala, el tiempo de espera en cada una y la duracion total del viaje. Puedes filtrar tu busqueda por vuelos directos o con escalas segun tu preferencia.'
    },
    {
      q: 'Que metodos de pago aceptan?',
      a: 'Aceptamos tarjetas de credito y debito. El formulario de pago solicita numero de tarjeta, fecha de vencimiento, CVV y nombre del titular. Si el pago falla se muestra un mensaje de error especifico sin guardar la reserva. Todos los pagos se procesan con cifrado SSL.'
    },
  ];

  let open = faqs.map(() => false);
  function toggle(i) { open[i] = !open[i]; open = [...open]; }
</script>

<div class="info-page">
  <div class="info-hero">
    <div class="info-hero__content">
      <div class="info-hero__icon">
        <svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="10"/>
          <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/>
          <line x1="12" y1="17" x2="12.01" y2="17"/>
        </svg>
      </div>
      <p class="info-hero__eyebrow">Broom AirLine</p>
      <h1 class="info-hero__title">Preguntas Frecuentes</h1>
      <p class="info-hero__subtitle">Resuelve tus dudas sobre reservas, pagos, asientos, cancelaciones y mas.</p>
    </div>
  </div>

  <div class="info-container">
    <button class="info-back" on:click={() => navigateTo('home')}>
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
        <line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>
      </svg>
      Volver al inicio
    </button>

    <div class="info-card">
      <h2 class="info-section-title" style="margin-top:0">Preguntas frecuentes</h2>
      <div class="info-faq">
        {#each faqs as faq, i}
          <div class="info-faq__item">
            <button class="info-faq__q" class:open={open[i]} on:click={() => toggle(i)}>
              <span>{faq.q}</span>
              <svg class="info-faq__chevron" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                <polyline points="6 9 12 15 18 9"/>
              </svg>
            </button>
            {#if open[i]}
              <div class="info-faq__a">{faq.a}</div>
            {/if}
          </div>
        {/each}
      </div>
    </div>

    <div class="info-card">
      <h2 class="info-section-title" style="margin-top:0">No encontraste tu respuesta?</h2>
      <p class="info-prose">Nuestro equipo de soporte esta disponible las 24 horas para atenderte. Tambien puedes consultar nuestro centro de ayuda o escribirnos directamente.</p>
      <div class="info-highlight">
        Escribenos a <strong>info@broomairline.com</strong> o llamanos al <strong>+502 2000-0000</strong>
      </div>
      <button class="info-contacto-submit" style="margin-top:1rem" on:click={() => navigateTo('contactanos')}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/>
        </svg>
        Ir a Contactanos
      </button>
    </div>
  </div>
</div>

// Agencia de Viajes/Movent/src/views/PreguntasFrecuentes.vue
<template>
  <div class="page">
    <Encabezado />
    <section class="info-hero" style="background-image: url('/empleado.png')">
      <div class="info-hero-overlay"></div>
      <div class="info-hero-content">
        <div class="info-hero-icon">
          <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
        </div>
        <p class="info-eyebrow">Movent</p>
        <h1 class="info-hero-title">Preguntas Frecuentes</h1>
        <p class="info-hero-subtitle">Respuestas a las dudas más comunes sobre reservaciones, pagos y políticas.</p>
      </div>
    </section>
    <div class="info-wrap">
      <button class="info-back" @click="$router.push('/informacion')">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>
        Volver a Información
      </button>
      <div class="info-section-body">
        <div v-for="(faq, i) in faqs" :key="i" class="info-faq">
          <button class="info-faq-q" :class="{ open: abierto[i] }" @click="toggle(i)">
            {{ faq.q }}
            <svg class="info-faq-chevron" :style="{ transform: abierto[i] ? 'rotate(180deg)' : 'rotate(0deg)' }"
              width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
              <polyline points="6 9 12 15 18 9"/>
            </svg>
          </button>
          <div v-if="abierto[i]" class="info-faq-a">{{ faq.a }}</div>
        </div>
        <div class="info-card" style="margin-top:1rem">
          <p class="info-prose" style="margin:0">
            ¿No encontraste tu respuesta? Escríbenos a <strong>info@movent.com</strong> o llámanos al <strong>+502 5754-5388</strong>
          </p>
        </div>
      </div>
    </div>
    <Piepagina />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import Encabezado from '../components/Encabezado.vue'
import Piepagina from '../components/Piepagina.vue'
import '../styles/informacion.css'

const faqs = [
  { q: '¿Cómo realizo una reservación?', a: 'Busca tu vuelo u hotel con los filtros disponibles (origen, destino, fechas, pasajeros, clase). Selecciona la opción deseada, revisa el itinerario completo con precio total y completa el proceso de pago. Recibirás un voucher PDF con tu código único #MVT-2026-XXXXXX.' },
  { q: '¿Qué tipos de asiento están disponibles?', a: 'Ofrecemos tres clases: Económica, Ejecutiva y Primera Clase. Cada una tiene precio diferenciado con características claramente visibles antes de reservar.' },
  { q: '¿Qué tipos de habitación están disponibles?', a: 'Ofrecemos cuatro tipos: Doble, Junior Suite, Suite y Gran Suite. Cada tipo muestra capacidad, tamaño de cama, metros cuadrados y servicios incluidos.' },
  { q: '¿Puedo reservar vuelo y hotel juntos?', a: 'Sí. En la búsqueda principal selecciona la pestaña "Vuelo + Hotel" para buscar paquetes combinados. También puedes crear tu propio paquete combinando un vuelo y un hospedaje en una sola transacción con código compartido.' },
  { q: '¿Cómo encuentro mi código de reservación?', a: 'Tu código es alfanumérico (ej. #MVT-2026-X9Y2Z5) y se envía al correo registrado inmediatamente después de confirmar el pago. También lo encuentras en "Mis Reservaciones" en tu perfil.' },
  { q: '¿Qué métodos de pago aceptan?', a: 'Aceptamos tarjetas de crédito y débito. El formulario solicita número de tarjeta, fecha de vencimiento, CVV y nombre del titular. Todos los pagos están protegidos con encriptación SSL.' },
  { q: '¿Puedo reservar para un grupo?', a: 'Sí. Selecciona la cantidad de pasajeros/huéspedes antes de buscar. Para reservas grupales se solicita información de cada persona. Todos los servicios del grupo comparten el mismo código de reservación de Movent.' },
  { q: '¿Dónde veo mis reservaciones anteriores?', a: 'En tu perfil, sección "Mis Reservaciones", encontrarás todas tus reservaciones categorizadas: activas, completadas y canceladas. Desde ahí también puedes descargar el voucher PDF.' },
]

const abierto = ref(faqs.map(() => false))
const toggle = (i) => { abierto.value[i] = !abierto.value[i] }
</script>
